// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/lawrencexu/funcate-server-go-sdk/internal"
	big "math/big"
)

var (
	authRefreshRequestFieldAuthSlug = big.NewInt(1 << 0)
)

type AuthRefreshRequest struct {
	// Auth slug defined in funcate.yaml
	AuthSlug string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AuthRefreshRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetAuthSlug sets the AuthSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthRefreshRequest) SetAuthSlug(authSlug string) {
	a.AuthSlug = authSlug
	a.require(authRefreshRequestFieldAuthSlug)
}

var (
	authWithPasswordRequestFieldAuthSlug = big.NewInt(1 << 0)
	authWithPasswordRequestFieldUsername = big.NewInt(1 << 1)
	authWithPasswordRequestFieldPassword = big.NewInt(1 << 2)
)

type AuthWithPasswordRequest struct {
	// Auth slug defined in funcate.yaml
	AuthSlug string `json:"-" url:"-"`
	// User's username
	Username string `json:"username" url:"-"`
	// User's password
	Password string `json:"password" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AuthWithPasswordRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetAuthSlug sets the AuthSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthWithPasswordRequest) SetAuthSlug(authSlug string) {
	a.AuthSlug = authSlug
	a.require(authWithPasswordRequestFieldAuthSlug)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthWithPasswordRequest) SetUsername(username string) {
	a.Username = username
	a.require(authWithPasswordRequestFieldUsername)
}

// SetPassword sets the Password field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthWithPasswordRequest) SetPassword(password string) {
	a.Password = password
	a.require(authWithPasswordRequestFieldPassword)
}

func (a *AuthWithPasswordRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler AuthWithPasswordRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*a = AuthWithPasswordRequest(body)
	return nil
}

func (a *AuthWithPasswordRequest) MarshalJSON() ([]byte, error) {
	type embed AuthWithPasswordRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getAuthMethodsRequestFieldAuthSlug = big.NewInt(1 << 0)
)

type GetAuthMethodsRequest struct {
	// Auth slug defined in funcate.yaml
	AuthSlug string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetAuthMethodsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetAuthSlug sets the AuthSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAuthMethodsRequest) SetAuthSlug(authSlug string) {
	g.AuthSlug = authSlug
	g.require(getAuthMethodsRequestFieldAuthSlug)
}

var (
	getPublicTokenRequestFieldAuthSlug = big.NewInt(1 << 0)
)

type GetPublicTokenRequest struct {
	// Auth slug defined in funcate.yaml
	AuthSlug string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetPublicTokenRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetAuthSlug sets the AuthSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPublicTokenRequest) SetAuthSlug(authSlug string) {
	g.AuthSlug = authSlug
	g.require(getPublicTokenRequestFieldAuthSlug)
}

var (
	authMethodsResponseFieldData    = big.NewInt(1 << 0)
	authMethodsResponseFieldStatus  = big.NewInt(1 << 1)
	authMethodsResponseFieldCode    = big.NewInt(1 << 2)
	authMethodsResponseFieldMessage = big.NewInt(1 << 3)
	authMethodsResponseFieldDetails = big.NewInt(1 << 4)
)

type AuthMethodsResponse struct {
	Data *AuthMethodsResponseData `json:"data,omitempty" url:"data,omitempty"`
	// HTTP status code
	Status int `json:"status" url:"status"`
	// General or specific code for the status, general like ok for 200, not_found for 404, specific like invalid_slug for 400
	Code string `json:"code" url:"code"`
	// Message to explain the status and code
	Message string         `json:"message" url:"message"`
	Details map[string]any `json:"details,omitempty" url:"details,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AuthMethodsResponse) GetData() *AuthMethodsResponseData {
	if a == nil {
		return nil
	}
	return a.Data
}

func (a *AuthMethodsResponse) GetStatus() int {
	if a == nil {
		return 0
	}
	return a.Status
}

func (a *AuthMethodsResponse) GetCode() string {
	if a == nil {
		return ""
	}
	return a.Code
}

func (a *AuthMethodsResponse) GetMessage() string {
	if a == nil {
		return ""
	}
	return a.Message
}

func (a *AuthMethodsResponse) GetDetails() map[string]any {
	if a == nil {
		return nil
	}
	return a.Details
}

func (a *AuthMethodsResponse) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AuthMethodsResponse) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthMethodsResponse) SetData(data *AuthMethodsResponseData) {
	a.Data = data
	a.require(authMethodsResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthMethodsResponse) SetStatus(status int) {
	a.Status = status
	a.require(authMethodsResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthMethodsResponse) SetCode(code string) {
	a.Code = code
	a.require(authMethodsResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthMethodsResponse) SetMessage(message string) {
	a.Message = message
	a.require(authMethodsResponseFieldMessage)
}

// SetDetails sets the Details field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthMethodsResponse) SetDetails(details map[string]any) {
	a.Details = details
	a.require(authMethodsResponseFieldDetails)
}

func (a *AuthMethodsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler AuthMethodsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AuthMethodsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AuthMethodsResponse) MarshalJSON() ([]byte, error) {
	type embed AuthMethodsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AuthMethodsResponse) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	authMethodsResponseDataFieldPassword = big.NewInt(1 << 0)
)

type AuthMethodsResponseData struct {
	Password *AuthMethodsResponseDataPassword `json:"password,omitempty" url:"password,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AuthMethodsResponseData) GetPassword() *AuthMethodsResponseDataPassword {
	if a == nil {
		return nil
	}
	return a.Password
}

func (a *AuthMethodsResponseData) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AuthMethodsResponseData) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetPassword sets the Password field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthMethodsResponseData) SetPassword(password *AuthMethodsResponseDataPassword) {
	a.Password = password
	a.require(authMethodsResponseDataFieldPassword)
}

func (a *AuthMethodsResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler AuthMethodsResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AuthMethodsResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AuthMethodsResponseData) MarshalJSON() ([]byte, error) {
	type embed AuthMethodsResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AuthMethodsResponseData) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	authMethodsResponseDataPasswordFieldEnabled      = big.NewInt(1 << 0)
	authMethodsResponseDataPasswordFieldWithUsername = big.NewInt(1 << 1)
)

type AuthMethodsResponseDataPassword struct {
	Enabled      bool `json:"enabled" url:"enabled"`
	WithUsername bool `json:"withUsername" url:"withUsername"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AuthMethodsResponseDataPassword) GetEnabled() bool {
	if a == nil {
		return false
	}
	return a.Enabled
}

func (a *AuthMethodsResponseDataPassword) GetWithUsername() bool {
	if a == nil {
		return false
	}
	return a.WithUsername
}

func (a *AuthMethodsResponseDataPassword) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AuthMethodsResponseDataPassword) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetEnabled sets the Enabled field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthMethodsResponseDataPassword) SetEnabled(enabled bool) {
	a.Enabled = enabled
	a.require(authMethodsResponseDataPasswordFieldEnabled)
}

// SetWithUsername sets the WithUsername field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthMethodsResponseDataPassword) SetWithUsername(withUsername bool) {
	a.WithUsername = withUsername
	a.require(authMethodsResponseDataPasswordFieldWithUsername)
}

func (a *AuthMethodsResponseDataPassword) UnmarshalJSON(data []byte) error {
	type unmarshaler AuthMethodsResponseDataPassword
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AuthMethodsResponseDataPassword(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AuthMethodsResponseDataPassword) MarshalJSON() ([]byte, error) {
	type embed AuthMethodsResponseDataPassword
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AuthMethodsResponseDataPassword) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	authPublicResponseFieldData    = big.NewInt(1 << 0)
	authPublicResponseFieldStatus  = big.NewInt(1 << 1)
	authPublicResponseFieldCode    = big.NewInt(1 << 2)
	authPublicResponseFieldMessage = big.NewInt(1 << 3)
	authPublicResponseFieldDetails = big.NewInt(1 << 4)
)

type AuthPublicResponse struct {
	Data *AuthPublicResponseData `json:"data,omitempty" url:"data,omitempty"`
	// HTTP status code
	Status int `json:"status" url:"status"`
	// General or specific code for the status, general like ok for 200, not_found for 404, specific like invalid_slug for 400
	Code string `json:"code" url:"code"`
	// Message to explain the status and code
	Message string         `json:"message" url:"message"`
	Details map[string]any `json:"details,omitempty" url:"details,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AuthPublicResponse) GetData() *AuthPublicResponseData {
	if a == nil {
		return nil
	}
	return a.Data
}

func (a *AuthPublicResponse) GetStatus() int {
	if a == nil {
		return 0
	}
	return a.Status
}

func (a *AuthPublicResponse) GetCode() string {
	if a == nil {
		return ""
	}
	return a.Code
}

func (a *AuthPublicResponse) GetMessage() string {
	if a == nil {
		return ""
	}
	return a.Message
}

func (a *AuthPublicResponse) GetDetails() map[string]any {
	if a == nil {
		return nil
	}
	return a.Details
}

func (a *AuthPublicResponse) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AuthPublicResponse) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthPublicResponse) SetData(data *AuthPublicResponseData) {
	a.Data = data
	a.require(authPublicResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthPublicResponse) SetStatus(status int) {
	a.Status = status
	a.require(authPublicResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthPublicResponse) SetCode(code string) {
	a.Code = code
	a.require(authPublicResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthPublicResponse) SetMessage(message string) {
	a.Message = message
	a.require(authPublicResponseFieldMessage)
}

// SetDetails sets the Details field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthPublicResponse) SetDetails(details map[string]any) {
	a.Details = details
	a.require(authPublicResponseFieldDetails)
}

func (a *AuthPublicResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler AuthPublicResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AuthPublicResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AuthPublicResponse) MarshalJSON() ([]byte, error) {
	type embed AuthPublicResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AuthPublicResponse) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	authPublicResponseDataFieldToken          = big.NewInt(1 << 0)
	authPublicResponseDataFieldTokenExpiresIn = big.NewInt(1 << 1)
)

type AuthPublicResponseData struct {
	// Public JWT token
	Token string `json:"token" url:"token"`
	// Token expiration time in seconds
	TokenExpiresIn int `json:"tokenExpiresIn" url:"tokenExpiresIn"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AuthPublicResponseData) GetToken() string {
	if a == nil {
		return ""
	}
	return a.Token
}

func (a *AuthPublicResponseData) GetTokenExpiresIn() int {
	if a == nil {
		return 0
	}
	return a.TokenExpiresIn
}

func (a *AuthPublicResponseData) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AuthPublicResponseData) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetToken sets the Token field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthPublicResponseData) SetToken(token string) {
	a.Token = token
	a.require(authPublicResponseDataFieldToken)
}

// SetTokenExpiresIn sets the TokenExpiresIn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthPublicResponseData) SetTokenExpiresIn(tokenExpiresIn int) {
	a.TokenExpiresIn = tokenExpiresIn
	a.require(authPublicResponseDataFieldTokenExpiresIn)
}

func (a *AuthPublicResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler AuthPublicResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AuthPublicResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AuthPublicResponseData) MarshalJSON() ([]byte, error) {
	type embed AuthPublicResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AuthPublicResponseData) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	authRefreshResponseFieldData    = big.NewInt(1 << 0)
	authRefreshResponseFieldStatus  = big.NewInt(1 << 1)
	authRefreshResponseFieldCode    = big.NewInt(1 << 2)
	authRefreshResponseFieldMessage = big.NewInt(1 << 3)
	authRefreshResponseFieldDetails = big.NewInt(1 << 4)
)

type AuthRefreshResponse struct {
	Data *AuthRefreshResponseData `json:"data,omitempty" url:"data,omitempty"`
	// HTTP status code
	Status int `json:"status" url:"status"`
	// General or specific code for the status, general like ok for 200, not_found for 404, specific like invalid_slug for 400
	Code string `json:"code" url:"code"`
	// Message to explain the status and code
	Message string         `json:"message" url:"message"`
	Details map[string]any `json:"details,omitempty" url:"details,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AuthRefreshResponse) GetData() *AuthRefreshResponseData {
	if a == nil {
		return nil
	}
	return a.Data
}

func (a *AuthRefreshResponse) GetStatus() int {
	if a == nil {
		return 0
	}
	return a.Status
}

func (a *AuthRefreshResponse) GetCode() string {
	if a == nil {
		return ""
	}
	return a.Code
}

func (a *AuthRefreshResponse) GetMessage() string {
	if a == nil {
		return ""
	}
	return a.Message
}

func (a *AuthRefreshResponse) GetDetails() map[string]any {
	if a == nil {
		return nil
	}
	return a.Details
}

func (a *AuthRefreshResponse) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AuthRefreshResponse) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthRefreshResponse) SetData(data *AuthRefreshResponseData) {
	a.Data = data
	a.require(authRefreshResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthRefreshResponse) SetStatus(status int) {
	a.Status = status
	a.require(authRefreshResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthRefreshResponse) SetCode(code string) {
	a.Code = code
	a.require(authRefreshResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthRefreshResponse) SetMessage(message string) {
	a.Message = message
	a.require(authRefreshResponseFieldMessage)
}

// SetDetails sets the Details field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthRefreshResponse) SetDetails(details map[string]any) {
	a.Details = details
	a.require(authRefreshResponseFieldDetails)
}

func (a *AuthRefreshResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler AuthRefreshResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AuthRefreshResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AuthRefreshResponse) MarshalJSON() ([]byte, error) {
	type embed AuthRefreshResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AuthRefreshResponse) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	authRefreshResponseDataFieldToken          = big.NewInt(1 << 0)
	authRefreshResponseDataFieldTokenExpiresIn = big.NewInt(1 << 1)
)

type AuthRefreshResponseData struct {
	// New JWT token
	Token string `json:"token" url:"token"`
	// Token expiration time in seconds
	TokenExpiresIn int `json:"tokenExpiresIn" url:"tokenExpiresIn"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AuthRefreshResponseData) GetToken() string {
	if a == nil {
		return ""
	}
	return a.Token
}

func (a *AuthRefreshResponseData) GetTokenExpiresIn() int {
	if a == nil {
		return 0
	}
	return a.TokenExpiresIn
}

func (a *AuthRefreshResponseData) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AuthRefreshResponseData) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetToken sets the Token field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthRefreshResponseData) SetToken(token string) {
	a.Token = token
	a.require(authRefreshResponseDataFieldToken)
}

// SetTokenExpiresIn sets the TokenExpiresIn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthRefreshResponseData) SetTokenExpiresIn(tokenExpiresIn int) {
	a.TokenExpiresIn = tokenExpiresIn
	a.require(authRefreshResponseDataFieldTokenExpiresIn)
}

func (a *AuthRefreshResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler AuthRefreshResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AuthRefreshResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AuthRefreshResponseData) MarshalJSON() ([]byte, error) {
	type embed AuthRefreshResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AuthRefreshResponseData) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	authWithPasswordResponseFieldData    = big.NewInt(1 << 0)
	authWithPasswordResponseFieldStatus  = big.NewInt(1 << 1)
	authWithPasswordResponseFieldCode    = big.NewInt(1 << 2)
	authWithPasswordResponseFieldMessage = big.NewInt(1 << 3)
	authWithPasswordResponseFieldDetails = big.NewInt(1 << 4)
)

type AuthWithPasswordResponse struct {
	Data *AuthWithPasswordResponseData `json:"data,omitempty" url:"data,omitempty"`
	// HTTP status code
	Status int `json:"status" url:"status"`
	// General or specific code for the status, general like ok for 200, not_found for 404, specific like invalid_slug for 400
	Code string `json:"code" url:"code"`
	// Message to explain the status and code
	Message string         `json:"message" url:"message"`
	Details map[string]any `json:"details,omitempty" url:"details,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AuthWithPasswordResponse) GetData() *AuthWithPasswordResponseData {
	if a == nil {
		return nil
	}
	return a.Data
}

func (a *AuthWithPasswordResponse) GetStatus() int {
	if a == nil {
		return 0
	}
	return a.Status
}

func (a *AuthWithPasswordResponse) GetCode() string {
	if a == nil {
		return ""
	}
	return a.Code
}

func (a *AuthWithPasswordResponse) GetMessage() string {
	if a == nil {
		return ""
	}
	return a.Message
}

func (a *AuthWithPasswordResponse) GetDetails() map[string]any {
	if a == nil {
		return nil
	}
	return a.Details
}

func (a *AuthWithPasswordResponse) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AuthWithPasswordResponse) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthWithPasswordResponse) SetData(data *AuthWithPasswordResponseData) {
	a.Data = data
	a.require(authWithPasswordResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthWithPasswordResponse) SetStatus(status int) {
	a.Status = status
	a.require(authWithPasswordResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthWithPasswordResponse) SetCode(code string) {
	a.Code = code
	a.require(authWithPasswordResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthWithPasswordResponse) SetMessage(message string) {
	a.Message = message
	a.require(authWithPasswordResponseFieldMessage)
}

// SetDetails sets the Details field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthWithPasswordResponse) SetDetails(details map[string]any) {
	a.Details = details
	a.require(authWithPasswordResponseFieldDetails)
}

func (a *AuthWithPasswordResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler AuthWithPasswordResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AuthWithPasswordResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AuthWithPasswordResponse) MarshalJSON() ([]byte, error) {
	type embed AuthWithPasswordResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AuthWithPasswordResponse) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	authWithPasswordResponseDataFieldToken          = big.NewInt(1 << 0)
	authWithPasswordResponseDataFieldTokenExpiresIn = big.NewInt(1 << 1)
	authWithPasswordResponseDataFieldUser           = big.NewInt(1 << 2)
)

type AuthWithPasswordResponseData struct {
	// JWT token for authentication
	Token string `json:"token" url:"token"`
	// Token expiration time in seconds
	TokenExpiresIn int   `json:"tokenExpiresIn" url:"tokenExpiresIn"`
	User           *User `json:"user" url:"user"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AuthWithPasswordResponseData) GetToken() string {
	if a == nil {
		return ""
	}
	return a.Token
}

func (a *AuthWithPasswordResponseData) GetTokenExpiresIn() int {
	if a == nil {
		return 0
	}
	return a.TokenExpiresIn
}

func (a *AuthWithPasswordResponseData) GetUser() *User {
	if a == nil {
		return nil
	}
	return a.User
}

func (a *AuthWithPasswordResponseData) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AuthWithPasswordResponseData) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetToken sets the Token field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthWithPasswordResponseData) SetToken(token string) {
	a.Token = token
	a.require(authWithPasswordResponseDataFieldToken)
}

// SetTokenExpiresIn sets the TokenExpiresIn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthWithPasswordResponseData) SetTokenExpiresIn(tokenExpiresIn int) {
	a.TokenExpiresIn = tokenExpiresIn
	a.require(authWithPasswordResponseDataFieldTokenExpiresIn)
}

// SetUser sets the User field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthWithPasswordResponseData) SetUser(user *User) {
	a.User = user
	a.require(authWithPasswordResponseDataFieldUser)
}

func (a *AuthWithPasswordResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler AuthWithPasswordResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AuthWithPasswordResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AuthWithPasswordResponseData) MarshalJSON() ([]byte, error) {
	type embed AuthWithPasswordResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AuthWithPasswordResponseData) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}
