// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/lawrencexu/funcate-server-go-sdk/internal"
	io "io"
	big "math/big"
)

var (
	deleteFileRequestFieldBucketSlug = big.NewInt(1 << 0)
	deleteFileRequestFieldFileID     = big.NewInt(1 << 1)
)

type DeleteFileRequest struct {
	// Slug of the bucket
	BucketSlug string `json:"-" url:"-"`
	FileID     string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteFileRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetBucketSlug sets the BucketSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteFileRequest) SetBucketSlug(bucketSlug string) {
	d.BucketSlug = bucketSlug
	d.require(deleteFileRequestFieldBucketSlug)
}

// SetFileID sets the FileID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteFileRequest) SetFileID(fileID string) {
	d.FileID = fileID
	d.require(deleteFileRequestFieldFileID)
}

var (
	downloadFileRequestFieldBucketSlug = big.NewInt(1 << 0)
	downloadFileRequestFieldFileID     = big.NewInt(1 << 1)
)

type DownloadFileRequest struct {
	// Slug of the bucket
	BucketSlug string `json:"-" url:"-"`
	// File ID, max length 36, first char must be alphanumeric, allowed chars: a-z A-Z 0-9 . - _
	FileID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DownloadFileRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetBucketSlug sets the BucketSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DownloadFileRequest) SetBucketSlug(bucketSlug string) {
	d.BucketSlug = bucketSlug
	d.require(downloadFileRequestFieldBucketSlug)
}

// SetFileID sets the FileID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DownloadFileRequest) SetFileID(fileID string) {
	d.FileID = fileID
	d.require(downloadFileRequestFieldFileID)
}

var (
	getFileRequestFieldBucketSlug = big.NewInt(1 << 0)
	getFileRequestFieldFileID     = big.NewInt(1 << 1)
)

type GetFileRequest struct {
	// Slug of the bucket
	BucketSlug string `json:"-" url:"-"`
	// File ID, max length 36, first char must be alphanumeric, allowed chars: a-z A-Z 0-9 . - _
	FileID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetFileRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetBucketSlug sets the BucketSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFileRequest) SetBucketSlug(bucketSlug string) {
	g.BucketSlug = bucketSlug
	g.require(getFileRequestFieldBucketSlug)
}

// SetFileID sets the FileID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFileRequest) SetFileID(fileID string) {
	g.FileID = fileID
	g.require(getFileRequestFieldFileID)
}

var (
	listFilesRequestFieldBucketSlug = big.NewInt(1 << 0)
	listFilesRequestFieldPage       = big.NewInt(1 << 1)
	listFilesRequestFieldPerPage    = big.NewInt(1 << 2)
	listFilesRequestFieldSort       = big.NewInt(1 << 3)
	listFilesRequestFieldFilter     = big.NewInt(1 << 4)
	listFilesRequestFieldFields     = big.NewInt(1 << 5)
)

type ListFilesRequest struct {
	// Slug of the bucket
	BucketSlug string `json:"-" url:"-"`
	// The page (aka. offset) of the paginated list (default to 1).
	Page *int `json:"-" url:"page,omitempty"`
	// The max returned files per page (default to 30).
	PerPage *int `json:"-" url:"perPage,omitempty"`
	// Specify the ORDER BY fields. Add - / + (default) in front of the attribute for DESC / ASC order, e.g.: // DESC by created and ASC by name ?sort=-created,name
	Sort *string `json:"-" url:"sort,omitempty"`
	// Filter expression to filter/search the returned files list, e.g.: ?filter=(name~'report' && size>1024)
	// The syntax basically follows the format OPERAND OPERATOR OPERAND, where: OPERAND - could be any field literal, string (single or double quoted), number, null, true, false OPERATOR - is one of: = Equal != NOT equal > Greater than >= Greater than or equal < Less than <= Less than or equal ~ Contains (for strings) !~ NOT contains (for strings) To group and combine several expressions you can use parenthesis (...), && (AND) and || (OR) tokens. Single line comments are also supported: // Example comment.
	Filter *string `json:"-" url:"filter,omitempty"`
	// Comma separated string of the fields to return in the JSON response (by default returns all fields). Ex.:?fields=id,name,size_bytes
	Fields *string `json:"-" url:"fields,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListFilesRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetBucketSlug sets the BucketSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFilesRequest) SetBucketSlug(bucketSlug string) {
	l.BucketSlug = bucketSlug
	l.require(listFilesRequestFieldBucketSlug)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFilesRequest) SetPage(page *int) {
	l.Page = page
	l.require(listFilesRequestFieldPage)
}

// SetPerPage sets the PerPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFilesRequest) SetPerPage(perPage *int) {
	l.PerPage = perPage
	l.require(listFilesRequestFieldPerPage)
}

// SetSort sets the Sort field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFilesRequest) SetSort(sort *string) {
	l.Sort = sort
	l.require(listFilesRequestFieldSort)
}

// SetFilter sets the Filter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFilesRequest) SetFilter(filter *string) {
	l.Filter = filter
	l.require(listFilesRequestFieldFilter)
}

// SetFields sets the Fields field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFilesRequest) SetFields(fields *string) {
	l.Fields = fields
	l.require(listFilesRequestFieldFields)
}

var (
	deleteFileResponseFieldData    = big.NewInt(1 << 0)
	deleteFileResponseFieldStatus  = big.NewInt(1 << 1)
	deleteFileResponseFieldCode    = big.NewInt(1 << 2)
	deleteFileResponseFieldMessage = big.NewInt(1 << 3)
	deleteFileResponseFieldDetails = big.NewInt(1 << 4)
)

type DeleteFileResponse struct {
	Data *File `json:"data,omitempty" url:"data,omitempty"`
	// HTTP status code
	Status int `json:"status" url:"status"`
	// General or specific code for the status, general like ok for 200, not_found for 404, specific like invalid_slug for 400
	Code string `json:"code" url:"code"`
	// Message to explain the status and code
	Message string         `json:"message" url:"message"`
	Details map[string]any `json:"details,omitempty" url:"details,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeleteFileResponse) GetData() *File {
	if d == nil {
		return nil
	}
	return d.Data
}

func (d *DeleteFileResponse) GetStatus() int {
	if d == nil {
		return 0
	}
	return d.Status
}

func (d *DeleteFileResponse) GetCode() string {
	if d == nil {
		return ""
	}
	return d.Code
}

func (d *DeleteFileResponse) GetMessage() string {
	if d == nil {
		return ""
	}
	return d.Message
}

func (d *DeleteFileResponse) GetDetails() map[string]any {
	if d == nil {
		return nil
	}
	return d.Details
}

func (d *DeleteFileResponse) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeleteFileResponse) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteFileResponse) SetData(data *File) {
	d.Data = data
	d.require(deleteFileResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteFileResponse) SetStatus(status int) {
	d.Status = status
	d.require(deleteFileResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteFileResponse) SetCode(code string) {
	d.Code = code
	d.require(deleteFileResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteFileResponse) SetMessage(message string) {
	d.Message = message
	d.require(deleteFileResponseFieldMessage)
}

// SetDetails sets the Details field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteFileResponse) SetDetails(details map[string]any) {
	d.Details = details
	d.require(deleteFileResponseFieldDetails)
}

func (d *DeleteFileResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteFileResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteFileResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteFileResponse) MarshalJSON() ([]byte, error) {
	type embed DeleteFileResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeleteFileResponse) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	fileFieldID          = big.NewInt(1 << 0)
	fileFieldBucketSlug  = big.NewInt(1 << 1)
	fileFieldContentType = big.NewInt(1 << 2)
	fileFieldSizeBytes   = big.NewInt(1 << 3)
	fileFieldCreatedAt   = big.NewInt(1 << 4)
	fileFieldUpdatedAt   = big.NewInt(1 << 5)
)

type File struct {
	// File ID, max length 36, first char must be alphanumeric, allowed chars: a-z A-Z 0-9 . - _
	ID string `json:"id" url:"id"`
	// Slug of the containing bucket
	BucketSlug string `json:"bucketSlug" url:"bucketSlug"`
	// Content type of the file
	ContentType string `json:"contentType" url:"contentType"`
	// File size in bytes
	SizeBytes int64 `json:"sizeBytes" url:"sizeBytes"`
	// Creation timestamp
	CreatedAt int64 `json:"createdAt" url:"createdAt"`
	// Last update timestamp
	UpdatedAt int64 `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *File) GetID() string {
	if f == nil {
		return ""
	}
	return f.ID
}

func (f *File) GetBucketSlug() string {
	if f == nil {
		return ""
	}
	return f.BucketSlug
}

func (f *File) GetContentType() string {
	if f == nil {
		return ""
	}
	return f.ContentType
}

func (f *File) GetSizeBytes() int64 {
	if f == nil {
		return 0
	}
	return f.SizeBytes
}

func (f *File) GetCreatedAt() int64 {
	if f == nil {
		return 0
	}
	return f.CreatedAt
}

func (f *File) GetUpdatedAt() int64 {
	if f == nil {
		return 0
	}
	return f.UpdatedAt
}

func (f *File) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *File) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *File) SetID(id string) {
	f.ID = id
	f.require(fileFieldID)
}

// SetBucketSlug sets the BucketSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *File) SetBucketSlug(bucketSlug string) {
	f.BucketSlug = bucketSlug
	f.require(fileFieldBucketSlug)
}

// SetContentType sets the ContentType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *File) SetContentType(contentType string) {
	f.ContentType = contentType
	f.require(fileFieldContentType)
}

// SetSizeBytes sets the SizeBytes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *File) SetSizeBytes(sizeBytes int64) {
	f.SizeBytes = sizeBytes
	f.require(fileFieldSizeBytes)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *File) SetCreatedAt(createdAt int64) {
	f.CreatedAt = createdAt
	f.require(fileFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *File) SetUpdatedAt(updatedAt int64) {
	f.UpdatedAt = updatedAt
	f.require(fileFieldUpdatedAt)
}

func (f *File) UnmarshalJSON(data []byte) error {
	type unmarshaler File
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = File(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *File) MarshalJSON() ([]byte, error) {
	type embed File
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *File) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

var (
	getFileResponseFieldData    = big.NewInt(1 << 0)
	getFileResponseFieldStatus  = big.NewInt(1 << 1)
	getFileResponseFieldCode    = big.NewInt(1 << 2)
	getFileResponseFieldMessage = big.NewInt(1 << 3)
	getFileResponseFieldDetails = big.NewInt(1 << 4)
)

type GetFileResponse struct {
	Data *File `json:"data,omitempty" url:"data,omitempty"`
	// HTTP status code
	Status int `json:"status" url:"status"`
	// General or specific code for the status, general like ok for 200, not_found for 404, specific like invalid_slug for 400
	Code string `json:"code" url:"code"`
	// Message to explain the status and code
	Message string         `json:"message" url:"message"`
	Details map[string]any `json:"details,omitempty" url:"details,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetFileResponse) GetData() *File {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetFileResponse) GetStatus() int {
	if g == nil {
		return 0
	}
	return g.Status
}

func (g *GetFileResponse) GetCode() string {
	if g == nil {
		return ""
	}
	return g.Code
}

func (g *GetFileResponse) GetMessage() string {
	if g == nil {
		return ""
	}
	return g.Message
}

func (g *GetFileResponse) GetDetails() map[string]any {
	if g == nil {
		return nil
	}
	return g.Details
}

func (g *GetFileResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetFileResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFileResponse) SetData(data *File) {
	g.Data = data
	g.require(getFileResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFileResponse) SetStatus(status int) {
	g.Status = status
	g.require(getFileResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFileResponse) SetCode(code string) {
	g.Code = code
	g.require(getFileResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFileResponse) SetMessage(message string) {
	g.Message = message
	g.require(getFileResponseFieldMessage)
}

// SetDetails sets the Details field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFileResponse) SetDetails(details map[string]any) {
	g.Details = details
	g.require(getFileResponseFieldDetails)
}

func (g *GetFileResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetFileResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetFileResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetFileResponse) MarshalJSON() ([]byte, error) {
	type embed GetFileResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetFileResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	listFilesResponseFieldData    = big.NewInt(1 << 0)
	listFilesResponseFieldStatus  = big.NewInt(1 << 1)
	listFilesResponseFieldCode    = big.NewInt(1 << 2)
	listFilesResponseFieldMessage = big.NewInt(1 << 3)
	listFilesResponseFieldDetails = big.NewInt(1 << 4)
)

type ListFilesResponse struct {
	Data *ListFilesResponseData `json:"data,omitempty" url:"data,omitempty"`
	// HTTP status code
	Status int `json:"status" url:"status"`
	// General or specific code for the status, general like ok for 200, not_found for 404, specific like invalid_slug for 400
	Code string `json:"code" url:"code"`
	// Message to explain the status and code
	Message string         `json:"message" url:"message"`
	Details map[string]any `json:"details,omitempty" url:"details,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListFilesResponse) GetData() *ListFilesResponseData {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListFilesResponse) GetStatus() int {
	if l == nil {
		return 0
	}
	return l.Status
}

func (l *ListFilesResponse) GetCode() string {
	if l == nil {
		return ""
	}
	return l.Code
}

func (l *ListFilesResponse) GetMessage() string {
	if l == nil {
		return ""
	}
	return l.Message
}

func (l *ListFilesResponse) GetDetails() map[string]any {
	if l == nil {
		return nil
	}
	return l.Details
}

func (l *ListFilesResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListFilesResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFilesResponse) SetData(data *ListFilesResponseData) {
	l.Data = data
	l.require(listFilesResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFilesResponse) SetStatus(status int) {
	l.Status = status
	l.require(listFilesResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFilesResponse) SetCode(code string) {
	l.Code = code
	l.require(listFilesResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFilesResponse) SetMessage(message string) {
	l.Message = message
	l.require(listFilesResponseFieldMessage)
}

// SetDetails sets the Details field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFilesResponse) SetDetails(details map[string]any) {
	l.Details = details
	l.require(listFilesResponseFieldDetails)
}

func (l *ListFilesResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListFilesResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListFilesResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListFilesResponse) MarshalJSON() ([]byte, error) {
	type embed ListFilesResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListFilesResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	listFilesResponseDataFieldItems      = big.NewInt(1 << 0)
	listFilesResponseDataFieldPage       = big.NewInt(1 << 1)
	listFilesResponseDataFieldPerPage    = big.NewInt(1 << 2)
	listFilesResponseDataFieldTotalItems = big.NewInt(1 << 3)
	listFilesResponseDataFieldTotalPages = big.NewInt(1 << 4)
)

type ListFilesResponseData struct {
	// List of files
	Items []*File `json:"items,omitempty" url:"items,omitempty"`
	// Current page number
	Page *int `json:"page,omitempty" url:"page,omitempty"`
	// Items per page
	PerPage *int `json:"perPage,omitempty" url:"perPage,omitempty"`
	// Total number of items
	TotalItems *int `json:"totalItems,omitempty" url:"totalItems,omitempty"`
	// Total number of pages
	TotalPages *int `json:"totalPages,omitempty" url:"totalPages,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListFilesResponseData) GetItems() []*File {
	if l == nil {
		return nil
	}
	return l.Items
}

func (l *ListFilesResponseData) GetPage() *int {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListFilesResponseData) GetPerPage() *int {
	if l == nil {
		return nil
	}
	return l.PerPage
}

func (l *ListFilesResponseData) GetTotalItems() *int {
	if l == nil {
		return nil
	}
	return l.TotalItems
}

func (l *ListFilesResponseData) GetTotalPages() *int {
	if l == nil {
		return nil
	}
	return l.TotalPages
}

func (l *ListFilesResponseData) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListFilesResponseData) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFilesResponseData) SetItems(items []*File) {
	l.Items = items
	l.require(listFilesResponseDataFieldItems)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFilesResponseData) SetPage(page *int) {
	l.Page = page
	l.require(listFilesResponseDataFieldPage)
}

// SetPerPage sets the PerPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFilesResponseData) SetPerPage(perPage *int) {
	l.PerPage = perPage
	l.require(listFilesResponseDataFieldPerPage)
}

// SetTotalItems sets the TotalItems field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFilesResponseData) SetTotalItems(totalItems *int) {
	l.TotalItems = totalItems
	l.require(listFilesResponseDataFieldTotalItems)
}

// SetTotalPages sets the TotalPages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFilesResponseData) SetTotalPages(totalPages *int) {
	l.TotalPages = totalPages
	l.require(listFilesResponseDataFieldTotalPages)
}

func (l *ListFilesResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler ListFilesResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListFilesResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListFilesResponseData) MarshalJSON() ([]byte, error) {
	type embed ListFilesResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListFilesResponseData) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	uploadFileResponseFieldData    = big.NewInt(1 << 0)
	uploadFileResponseFieldStatus  = big.NewInt(1 << 1)
	uploadFileResponseFieldCode    = big.NewInt(1 << 2)
	uploadFileResponseFieldMessage = big.NewInt(1 << 3)
	uploadFileResponseFieldDetails = big.NewInt(1 << 4)
)

type UploadFileResponse struct {
	Data *File `json:"data,omitempty" url:"data,omitempty"`
	// HTTP status code
	Status int `json:"status" url:"status"`
	// General or specific code for the status, general like ok for 200, not_found for 404, specific like invalid_slug for 400
	Code string `json:"code" url:"code"`
	// Message to explain the status and code
	Message string         `json:"message" url:"message"`
	Details map[string]any `json:"details,omitempty" url:"details,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UploadFileResponse) GetData() *File {
	if u == nil {
		return nil
	}
	return u.Data
}

func (u *UploadFileResponse) GetStatus() int {
	if u == nil {
		return 0
	}
	return u.Status
}

func (u *UploadFileResponse) GetCode() string {
	if u == nil {
		return ""
	}
	return u.Code
}

func (u *UploadFileResponse) GetMessage() string {
	if u == nil {
		return ""
	}
	return u.Message
}

func (u *UploadFileResponse) GetDetails() map[string]any {
	if u == nil {
		return nil
	}
	return u.Details
}

func (u *UploadFileResponse) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UploadFileResponse) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UploadFileResponse) SetData(data *File) {
	u.Data = data
	u.require(uploadFileResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UploadFileResponse) SetStatus(status int) {
	u.Status = status
	u.require(uploadFileResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UploadFileResponse) SetCode(code string) {
	u.Code = code
	u.require(uploadFileResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UploadFileResponse) SetMessage(message string) {
	u.Message = message
	u.require(uploadFileResponseFieldMessage)
}

// SetDetails sets the Details field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UploadFileResponse) SetDetails(details map[string]any) {
	u.Details = details
	u.require(uploadFileResponseFieldDetails)
}

func (u *UploadFileResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UploadFileResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UploadFileResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UploadFileResponse) MarshalJSON() ([]byte, error) {
	type embed UploadFileResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UploadFileResponse) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	uploadFileRequestFieldBucketSlug = big.NewInt(1 << 0)
)

type UploadFileRequest struct {
	// Slug of the bucket
	BucketSlug string    `json:"-" url:"-"`
	Content    io.Reader `json:"-" url:"-"`
	// File id, File ID, max length 36, first char must be alphanumeric, allowed chars: a-z A-Z 0-9 . - _
	ID string `json:"id" url:"-"`
	// Content type of the file, valid MIME type
	ContentType string `json:"contentType" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UploadFileRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetBucketSlug sets the BucketSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UploadFileRequest) SetBucketSlug(bucketSlug string) {
	u.BucketSlug = bucketSlug
	u.require(uploadFileRequestFieldBucketSlug)
}

func (u *UploadFileRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler UploadFileRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UploadFileRequest(body)
	return nil
}

func (u *UploadFileRequest) MarshalJSON() ([]byte, error) {
	type embed UploadFileRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	viewFileRequestFieldBucketSlug = big.NewInt(1 << 0)
	viewFileRequestFieldFileID     = big.NewInt(1 << 1)
)

type ViewFileRequest struct {
	// Slug of the bucket
	BucketSlug string `json:"-" url:"-"`
	FileID     string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (v *ViewFileRequest) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetBucketSlug sets the BucketSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *ViewFileRequest) SetBucketSlug(bucketSlug string) {
	v.BucketSlug = bucketSlug
	v.require(viewFileRequestFieldBucketSlug)
}

// SetFileID sets the FileID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *ViewFileRequest) SetFileID(fileID string) {
	v.FileID = fileID
	v.require(viewFileRequestFieldFileID)
}
