// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/lawrencexu/funcate-server-go-sdk/internal"
	big "math/big"
)

var (
	createMessageRequestFieldAgentSlug = big.NewInt(1 << 0)
	createMessageRequestFieldOwnerID   = big.NewInt(1 << 1)
	createMessageRequestFieldSessionID = big.NewInt(1 << 2)
	createMessageRequestFieldAuthor    = big.NewInt(1 << 3)
	createMessageRequestFieldParts     = big.NewInt(1 << 4)
	createMessageRequestFieldStream    = big.NewInt(1 << 5)
)

type CreateMessageRequest struct {
	// Agent slug defined in funcate.yaml
	AgentSlug string `json:"-" url:"-"`
	// Owner identifier
	OwnerID string `json:"-" url:"-"`
	// Session identifier
	SessionID string `json:"-" url:"-"`
	// Message author
	Author CreateMessageRequestAuthor `json:"author" url:"-"`
	// Message parts
	Parts []*MessagePart `json:"parts" url:"-"`
	// Whether to stream the response as Server-Sent Events (SSE)
	Stream *bool `json:"stream,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateMessageRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAgentSlug sets the AgentSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMessageRequest) SetAgentSlug(agentSlug string) {
	c.AgentSlug = agentSlug
	c.require(createMessageRequestFieldAgentSlug)
}

// SetOwnerID sets the OwnerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMessageRequest) SetOwnerID(ownerID string) {
	c.OwnerID = ownerID
	c.require(createMessageRequestFieldOwnerID)
}

// SetSessionID sets the SessionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMessageRequest) SetSessionID(sessionID string) {
	c.SessionID = sessionID
	c.require(createMessageRequestFieldSessionID)
}

// SetAuthor sets the Author field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMessageRequest) SetAuthor(author CreateMessageRequestAuthor) {
	c.Author = author
	c.require(createMessageRequestFieldAuthor)
}

// SetParts sets the Parts field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMessageRequest) SetParts(parts []*MessagePart) {
	c.Parts = parts
	c.require(createMessageRequestFieldParts)
}

// SetStream sets the Stream field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMessageRequest) SetStream(stream *bool) {
	c.Stream = stream
	c.require(createMessageRequestFieldStream)
}

func (c *CreateMessageRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateMessageRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateMessageRequest(body)
	return nil
}

func (c *CreateMessageRequest) MarshalJSON() ([]byte, error) {
	type embed CreateMessageRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	listMessagesRequestFieldAgentSlug = big.NewInt(1 << 0)
	listMessagesRequestFieldOwnerID   = big.NewInt(1 << 1)
	listMessagesRequestFieldSessionID = big.NewInt(1 << 2)
	listMessagesRequestFieldPage      = big.NewInt(1 << 3)
	listMessagesRequestFieldPerPage   = big.NewInt(1 << 4)
	listMessagesRequestFieldSort      = big.NewInt(1 << 5)
	listMessagesRequestFieldFilter    = big.NewInt(1 << 6)
	listMessagesRequestFieldFields    = big.NewInt(1 << 7)
)

type ListMessagesRequest struct {
	// Agent slug defined in funcate.yaml
	AgentSlug string `json:"-" url:"-"`
	// Owner identifier
	OwnerID string `json:"-" url:"-"`
	// Session identifier
	SessionID string `json:"-" url:"-"`
	// The page (aka. offset) of the paginated list (default to 1).
	Page *int `json:"-" url:"page,omitempty"`
	// The max returned files per page (default to 30).
	PerPage *int `json:"-" url:"perPage,omitempty"`
	// Specify the ORDER BY fields. Add - / + (default) in front of the attribute for DESC / ASC order, e.g.: // DESC by created ?sort=-created_at
	Sort *string `json:"-" url:"sort,omitempty"`
	// Filter expression to filter/search the returned messages list, e.g.: ?filter=(author='user' && created_at>1732924800000)
	// The syntax basically follows the format OPERAND OPERATOR OPERAND, where: OPERAND - could be any field literal, string (single or double quoted), number, null, true, false OPERATOR - is one of: = Equal != NOT equal > Greater than >= Greater than or equal < Less than <= Less than or equal ~ Contains (for strings) !~ NOT contains (for strings) To group and combine several expressions you can use parenthesis (...), && (AND) and || (OR) tokens. Single line comments are also supported: // Example comment.
	Filter *string `json:"-" url:"filter,omitempty"`
	// Comma separated string of the fields to return in the JSON response (by default returns all fields). Ex.:?fields=id,author,created_at
	Fields *string `json:"-" url:"fields,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListMessagesRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetAgentSlug sets the AgentSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMessagesRequest) SetAgentSlug(agentSlug string) {
	l.AgentSlug = agentSlug
	l.require(listMessagesRequestFieldAgentSlug)
}

// SetOwnerID sets the OwnerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMessagesRequest) SetOwnerID(ownerID string) {
	l.OwnerID = ownerID
	l.require(listMessagesRequestFieldOwnerID)
}

// SetSessionID sets the SessionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMessagesRequest) SetSessionID(sessionID string) {
	l.SessionID = sessionID
	l.require(listMessagesRequestFieldSessionID)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMessagesRequest) SetPage(page *int) {
	l.Page = page
	l.require(listMessagesRequestFieldPage)
}

// SetPerPage sets the PerPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMessagesRequest) SetPerPage(perPage *int) {
	l.PerPage = perPage
	l.require(listMessagesRequestFieldPerPage)
}

// SetSort sets the Sort field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMessagesRequest) SetSort(sort *string) {
	l.Sort = sort
	l.require(listMessagesRequestFieldSort)
}

// SetFilter sets the Filter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMessagesRequest) SetFilter(filter *string) {
	l.Filter = filter
	l.require(listMessagesRequestFieldFilter)
}

// SetFields sets the Fields field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMessagesRequest) SetFields(fields *string) {
	l.Fields = fields
	l.require(listMessagesRequestFieldFields)
}

var (
	createMessageResponseFieldData    = big.NewInt(1 << 0)
	createMessageResponseFieldStatus  = big.NewInt(1 << 1)
	createMessageResponseFieldCode    = big.NewInt(1 << 2)
	createMessageResponseFieldMessage = big.NewInt(1 << 3)
	createMessageResponseFieldDetails = big.NewInt(1 << 4)
)

type CreateMessageResponse struct {
	Data *CreateMessageResponseData `json:"data,omitempty" url:"data,omitempty"`
	// HTTP status code
	Status int `json:"status" url:"status"`
	// General or specific code for the status, general like ok for 200, not_found for 404, specific like invalid_slug for 400
	Code string `json:"code" url:"code"`
	// Message to explain the status and code
	Message string         `json:"message" url:"message"`
	Details map[string]any `json:"details,omitempty" url:"details,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateMessageResponse) GetData() *CreateMessageResponseData {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *CreateMessageResponse) GetStatus() int {
	if c == nil {
		return 0
	}
	return c.Status
}

func (c *CreateMessageResponse) GetCode() string {
	if c == nil {
		return ""
	}
	return c.Code
}

func (c *CreateMessageResponse) GetMessage() string {
	if c == nil {
		return ""
	}
	return c.Message
}

func (c *CreateMessageResponse) GetDetails() map[string]any {
	if c == nil {
		return nil
	}
	return c.Details
}

func (c *CreateMessageResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateMessageResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMessageResponse) SetData(data *CreateMessageResponseData) {
	c.Data = data
	c.require(createMessageResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMessageResponse) SetStatus(status int) {
	c.Status = status
	c.require(createMessageResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMessageResponse) SetCode(code string) {
	c.Code = code
	c.require(createMessageResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMessageResponse) SetMessage(message string) {
	c.Message = message
	c.require(createMessageResponseFieldMessage)
}

// SetDetails sets the Details field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMessageResponse) SetDetails(details map[string]any) {
	c.Details = details
	c.require(createMessageResponseFieldDetails)
}

func (c *CreateMessageResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateMessageResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateMessageResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateMessageResponse) MarshalJSON() ([]byte, error) {
	type embed CreateMessageResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateMessageResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	createMessageResponseDataFieldMessage = big.NewInt(1 << 0)
)

type CreateMessageResponseData struct {
	Message *Message `json:"message" url:"message"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateMessageResponseData) GetMessage() *Message {
	if c == nil {
		return nil
	}
	return c.Message
}

func (c *CreateMessageResponseData) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateMessageResponseData) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMessageResponseData) SetMessage(message *Message) {
	c.Message = message
	c.require(createMessageResponseDataFieldMessage)
}

func (c *CreateMessageResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateMessageResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateMessageResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateMessageResponseData) MarshalJSON() ([]byte, error) {
	type embed CreateMessageResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateMessageResponseData) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	listMessagesResponseFieldData    = big.NewInt(1 << 0)
	listMessagesResponseFieldStatus  = big.NewInt(1 << 1)
	listMessagesResponseFieldCode    = big.NewInt(1 << 2)
	listMessagesResponseFieldMessage = big.NewInt(1 << 3)
	listMessagesResponseFieldDetails = big.NewInt(1 << 4)
)

type ListMessagesResponse struct {
	Data *ListMessagesResponseData `json:"data,omitempty" url:"data,omitempty"`
	// HTTP status code
	Status int `json:"status" url:"status"`
	// General or specific code for the status, general like ok for 200, not_found for 404, specific like invalid_slug for 400
	Code string `json:"code" url:"code"`
	// Message to explain the status and code
	Message string         `json:"message" url:"message"`
	Details map[string]any `json:"details,omitempty" url:"details,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListMessagesResponse) GetData() *ListMessagesResponseData {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListMessagesResponse) GetStatus() int {
	if l == nil {
		return 0
	}
	return l.Status
}

func (l *ListMessagesResponse) GetCode() string {
	if l == nil {
		return ""
	}
	return l.Code
}

func (l *ListMessagesResponse) GetMessage() string {
	if l == nil {
		return ""
	}
	return l.Message
}

func (l *ListMessagesResponse) GetDetails() map[string]any {
	if l == nil {
		return nil
	}
	return l.Details
}

func (l *ListMessagesResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListMessagesResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMessagesResponse) SetData(data *ListMessagesResponseData) {
	l.Data = data
	l.require(listMessagesResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMessagesResponse) SetStatus(status int) {
	l.Status = status
	l.require(listMessagesResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMessagesResponse) SetCode(code string) {
	l.Code = code
	l.require(listMessagesResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMessagesResponse) SetMessage(message string) {
	l.Message = message
	l.require(listMessagesResponseFieldMessage)
}

// SetDetails sets the Details field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMessagesResponse) SetDetails(details map[string]any) {
	l.Details = details
	l.require(listMessagesResponseFieldDetails)
}

func (l *ListMessagesResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListMessagesResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListMessagesResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListMessagesResponse) MarshalJSON() ([]byte, error) {
	type embed ListMessagesResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListMessagesResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	listMessagesResponseDataFieldItems      = big.NewInt(1 << 0)
	listMessagesResponseDataFieldPage       = big.NewInt(1 << 1)
	listMessagesResponseDataFieldPerPage    = big.NewInt(1 << 2)
	listMessagesResponseDataFieldTotalItems = big.NewInt(1 << 3)
	listMessagesResponseDataFieldTotalPages = big.NewInt(1 << 4)
)

type ListMessagesResponseData struct {
	Items []*Message `json:"items" url:"items"`
	// Current page number
	Page int `json:"page" url:"page"`
	// Items per page
	PerPage int `json:"perPage" url:"perPage"`
	// Total number of items
	TotalItems int `json:"totalItems" url:"totalItems"`
	// Total number of pages
	TotalPages int `json:"totalPages" url:"totalPages"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListMessagesResponseData) GetItems() []*Message {
	if l == nil {
		return nil
	}
	return l.Items
}

func (l *ListMessagesResponseData) GetPage() int {
	if l == nil {
		return 0
	}
	return l.Page
}

func (l *ListMessagesResponseData) GetPerPage() int {
	if l == nil {
		return 0
	}
	return l.PerPage
}

func (l *ListMessagesResponseData) GetTotalItems() int {
	if l == nil {
		return 0
	}
	return l.TotalItems
}

func (l *ListMessagesResponseData) GetTotalPages() int {
	if l == nil {
		return 0
	}
	return l.TotalPages
}

func (l *ListMessagesResponseData) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListMessagesResponseData) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMessagesResponseData) SetItems(items []*Message) {
	l.Items = items
	l.require(listMessagesResponseDataFieldItems)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMessagesResponseData) SetPage(page int) {
	l.Page = page
	l.require(listMessagesResponseDataFieldPage)
}

// SetPerPage sets the PerPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMessagesResponseData) SetPerPage(perPage int) {
	l.PerPage = perPage
	l.require(listMessagesResponseDataFieldPerPage)
}

// SetTotalItems sets the TotalItems field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMessagesResponseData) SetTotalItems(totalItems int) {
	l.TotalItems = totalItems
	l.require(listMessagesResponseDataFieldTotalItems)
}

// SetTotalPages sets the TotalPages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMessagesResponseData) SetTotalPages(totalPages int) {
	l.TotalPages = totalPages
	l.require(listMessagesResponseDataFieldTotalPages)
}

func (l *ListMessagesResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler ListMessagesResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListMessagesResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListMessagesResponseData) MarshalJSON() ([]byte, error) {
	type embed ListMessagesResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListMessagesResponseData) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	messageFieldAuthor          = big.NewInt(1 << 0)
	messageFieldID              = big.NewInt(1 << 1)
	messageFieldInvocationID    = big.NewInt(1 << 2)
	messageFieldCreatedAt       = big.NewInt(1 << 3)
	messageFieldPartial         = big.NewInt(1 << 4)
	messageFieldTurnComplete    = big.NewInt(1 << 5)
	messageFieldInterrupted     = big.NewInt(1 << 6)
	messageFieldErrorCode       = big.NewInt(1 << 7)
	messageFieldErrorMessage    = big.NewInt(1 << 8)
	messageFieldIsFinalResponse = big.NewInt(1 << 9)
	messageFieldParts           = big.NewInt(1 << 10)
)

type Message struct {
	// Message author (user, assistant, system)
	Author string `json:"author" url:"author"`
	// Unique message identifier
	ID string `json:"id" url:"id"`
	// Invocation identifier for tracking
	InvocationID string `json:"invocation_id" url:"invocation_id"`
	// Creation timestamp in milliseconds since epoch
	CreatedAt int64 `json:"created_at" url:"created_at"`
	// Whether the content is part of an unfinished content stream (streaming mode)
	Partial *bool `json:"partial,omitempty" url:"partial,omitempty"`
	// Whether the response from the model is complete (streaming mode)
	TurnComplete *bool `json:"turn_complete,omitempty" url:"turn_complete,omitempty"`
	// Whether LLM was interrupted when generating the content
	Interrupted *bool `json:"interrupted,omitempty" url:"interrupted,omitempty"`
	// Error code if the message generation failed
	ErrorCode *string `json:"error_code,omitempty" url:"error_code,omitempty"`
	// Error message if the message generation failed
	ErrorMessage *string `json:"error_message,omitempty" url:"error_message,omitempty"`
	// Whether this is the final response with all content for streaming mode
	IsFinalResponse *bool `json:"is_final_response,omitempty" url:"is_final_response,omitempty"`
	// Message parts (text, tool calls, tool responses)
	Parts []*MessagePart `json:"parts" url:"parts"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *Message) GetAuthor() string {
	if m == nil {
		return ""
	}
	return m.Author
}

func (m *Message) GetID() string {
	if m == nil {
		return ""
	}
	return m.ID
}

func (m *Message) GetInvocationID() string {
	if m == nil {
		return ""
	}
	return m.InvocationID
}

func (m *Message) GetCreatedAt() int64 {
	if m == nil {
		return 0
	}
	return m.CreatedAt
}

func (m *Message) GetPartial() *bool {
	if m == nil {
		return nil
	}
	return m.Partial
}

func (m *Message) GetTurnComplete() *bool {
	if m == nil {
		return nil
	}
	return m.TurnComplete
}

func (m *Message) GetInterrupted() *bool {
	if m == nil {
		return nil
	}
	return m.Interrupted
}

func (m *Message) GetErrorCode() *string {
	if m == nil {
		return nil
	}
	return m.ErrorCode
}

func (m *Message) GetErrorMessage() *string {
	if m == nil {
		return nil
	}
	return m.ErrorMessage
}

func (m *Message) GetIsFinalResponse() *bool {
	if m == nil {
		return nil
	}
	return m.IsFinalResponse
}

func (m *Message) GetParts() []*MessagePart {
	if m == nil {
		return nil
	}
	return m.Parts
}

func (m *Message) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *Message) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetAuthor sets the Author field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Message) SetAuthor(author string) {
	m.Author = author
	m.require(messageFieldAuthor)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Message) SetID(id string) {
	m.ID = id
	m.require(messageFieldID)
}

// SetInvocationID sets the InvocationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Message) SetInvocationID(invocationID string) {
	m.InvocationID = invocationID
	m.require(messageFieldInvocationID)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Message) SetCreatedAt(createdAt int64) {
	m.CreatedAt = createdAt
	m.require(messageFieldCreatedAt)
}

// SetPartial sets the Partial field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Message) SetPartial(partial *bool) {
	m.Partial = partial
	m.require(messageFieldPartial)
}

// SetTurnComplete sets the TurnComplete field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Message) SetTurnComplete(turnComplete *bool) {
	m.TurnComplete = turnComplete
	m.require(messageFieldTurnComplete)
}

// SetInterrupted sets the Interrupted field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Message) SetInterrupted(interrupted *bool) {
	m.Interrupted = interrupted
	m.require(messageFieldInterrupted)
}

// SetErrorCode sets the ErrorCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Message) SetErrorCode(errorCode *string) {
	m.ErrorCode = errorCode
	m.require(messageFieldErrorCode)
}

// SetErrorMessage sets the ErrorMessage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Message) SetErrorMessage(errorMessage *string) {
	m.ErrorMessage = errorMessage
	m.require(messageFieldErrorMessage)
}

// SetIsFinalResponse sets the IsFinalResponse field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Message) SetIsFinalResponse(isFinalResponse *bool) {
	m.IsFinalResponse = isFinalResponse
	m.require(messageFieldIsFinalResponse)
}

// SetParts sets the Parts field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Message) SetParts(parts []*MessagePart) {
	m.Parts = parts
	m.require(messageFieldParts)
}

func (m *Message) UnmarshalJSON(data []byte) error {
	type unmarshaler Message
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = Message(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *Message) MarshalJSON() ([]byte, error) {
	type embed Message
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *Message) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	messagePartFieldType         = big.NewInt(1 << 0)
	messagePartFieldText         = big.NewInt(1 << 1)
	messagePartFieldToolCall     = big.NewInt(1 << 2)
	messagePartFieldToolResponse = big.NewInt(1 << 3)
)

type MessagePart struct {
	// Type of message part
	Type MessagePartType `json:"type" url:"type"`
	// Text content (for type=text)
	Text         *string       `json:"text,omitempty" url:"text,omitempty"`
	ToolCall     *ToolCall     `json:"tool_call,omitempty" url:"tool_call,omitempty"`
	ToolResponse *ToolResponse `json:"tool_response,omitempty" url:"tool_response,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MessagePart) GetType() MessagePartType {
	if m == nil {
		return ""
	}
	return m.Type
}

func (m *MessagePart) GetText() *string {
	if m == nil {
		return nil
	}
	return m.Text
}

func (m *MessagePart) GetToolCall() *ToolCall {
	if m == nil {
		return nil
	}
	return m.ToolCall
}

func (m *MessagePart) GetToolResponse() *ToolResponse {
	if m == nil {
		return nil
	}
	return m.ToolResponse
}

func (m *MessagePart) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MessagePart) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MessagePart) SetType(type_ MessagePartType) {
	m.Type = type_
	m.require(messagePartFieldType)
}

// SetText sets the Text field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MessagePart) SetText(text *string) {
	m.Text = text
	m.require(messagePartFieldText)
}

// SetToolCall sets the ToolCall field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MessagePart) SetToolCall(toolCall *ToolCall) {
	m.ToolCall = toolCall
	m.require(messagePartFieldToolCall)
}

// SetToolResponse sets the ToolResponse field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MessagePart) SetToolResponse(toolResponse *ToolResponse) {
	m.ToolResponse = toolResponse
	m.require(messagePartFieldToolResponse)
}

func (m *MessagePart) UnmarshalJSON(data []byte) error {
	type unmarshaler MessagePart
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MessagePart(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MessagePart) MarshalJSON() ([]byte, error) {
	type embed MessagePart
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MessagePart) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

// Type of message part
type MessagePartType string

const (
	MessagePartTypeText         MessagePartType = "text"
	MessagePartTypeToolCall     MessagePartType = "tool_call"
	MessagePartTypeToolResponse MessagePartType = "tool_response"
)

func NewMessagePartTypeFromString(s string) (MessagePartType, error) {
	switch s {
	case "text":
		return MessagePartTypeText, nil
	case "tool_call":
		return MessagePartTypeToolCall, nil
	case "tool_response":
		return MessagePartTypeToolResponse, nil
	}
	var t MessagePartType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (m MessagePartType) Ptr() *MessagePartType {
	return &m
}

var (
	toolCallFieldID   = big.NewInt(1 << 0)
	toolCallFieldName = big.NewInt(1 << 1)
	toolCallFieldArgs = big.NewInt(1 << 2)
)

type ToolCall struct {
	// Tool call identifier
	ID string `json:"id" url:"id"`
	// Tool name
	Name string `json:"name" url:"name"`
	// Tool arguments as key-value pairs
	Args map[string]string `json:"args" url:"args"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *ToolCall) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *ToolCall) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *ToolCall) GetArgs() map[string]string {
	if t == nil {
		return nil
	}
	return t.Args
}

func (t *ToolCall) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *ToolCall) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *ToolCall) SetID(id string) {
	t.ID = id
	t.require(toolCallFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *ToolCall) SetName(name string) {
	t.Name = name
	t.require(toolCallFieldName)
}

// SetArgs sets the Args field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *ToolCall) SetArgs(args map[string]string) {
	t.Args = args
	t.require(toolCallFieldArgs)
}

func (t *ToolCall) UnmarshalJSON(data []byte) error {
	type unmarshaler ToolCall
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = ToolCall(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *ToolCall) MarshalJSON() ([]byte, error) {
	type embed ToolCall
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *ToolCall) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

var (
	toolResponseFieldID       = big.NewInt(1 << 0)
	toolResponseFieldName     = big.NewInt(1 << 1)
	toolResponseFieldResponse = big.NewInt(1 << 2)
	toolResponseFieldMetadata = big.NewInt(1 << 3)
)

type ToolResponse struct {
	// Tool response identifier
	ID string `json:"id" url:"id"`
	// Tool name
	Name string `json:"name" url:"name"`
	// Tool response content
	Response string                `json:"response" url:"response"`
	Metadata *ToolResponseMetadata `json:"metadata,omitempty" url:"metadata,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *ToolResponse) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *ToolResponse) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *ToolResponse) GetResponse() string {
	if t == nil {
		return ""
	}
	return t.Response
}

func (t *ToolResponse) GetMetadata() *ToolResponseMetadata {
	if t == nil {
		return nil
	}
	return t.Metadata
}

func (t *ToolResponse) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *ToolResponse) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *ToolResponse) SetID(id string) {
	t.ID = id
	t.require(toolResponseFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *ToolResponse) SetName(name string) {
	t.Name = name
	t.require(toolResponseFieldName)
}

// SetResponse sets the Response field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *ToolResponse) SetResponse(response string) {
	t.Response = response
	t.require(toolResponseFieldResponse)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *ToolResponse) SetMetadata(metadata *ToolResponseMetadata) {
	t.Metadata = metadata
	t.require(toolResponseFieldMetadata)
}

func (t *ToolResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ToolResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = ToolResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *ToolResponse) MarshalJSON() ([]byte, error) {
	type embed ToolResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *ToolResponse) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

var (
	toolResponseMetadataFieldIsHidden = big.NewInt(1 << 0)
	toolResponseMetadataFieldMessage  = big.NewInt(1 << 1)
)

type ToolResponseMetadata struct {
	// Whether the response is hidden from the user
	IsHidden bool `json:"is_hidden" url:"is_hidden"`
	// Additional metadata message
	Message *string `json:"message,omitempty" url:"message,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *ToolResponseMetadata) GetIsHidden() bool {
	if t == nil {
		return false
	}
	return t.IsHidden
}

func (t *ToolResponseMetadata) GetMessage() *string {
	if t == nil {
		return nil
	}
	return t.Message
}

func (t *ToolResponseMetadata) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *ToolResponseMetadata) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetIsHidden sets the IsHidden field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *ToolResponseMetadata) SetIsHidden(isHidden bool) {
	t.IsHidden = isHidden
	t.require(toolResponseMetadataFieldIsHidden)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *ToolResponseMetadata) SetMessage(message *string) {
	t.Message = message
	t.require(toolResponseMetadataFieldMessage)
}

func (t *ToolResponseMetadata) UnmarshalJSON(data []byte) error {
	type unmarshaler ToolResponseMetadata
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = ToolResponseMetadata(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *ToolResponseMetadata) MarshalJSON() ([]byte, error) {
	type embed ToolResponseMetadata
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *ToolResponseMetadata) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// Message author
type CreateMessageRequestAuthor string

const (
	CreateMessageRequestAuthorUser      CreateMessageRequestAuthor = "user"
	CreateMessageRequestAuthorAssistant CreateMessageRequestAuthor = "assistant"
	CreateMessageRequestAuthorSystem    CreateMessageRequestAuthor = "system"
)

func NewCreateMessageRequestAuthorFromString(s string) (CreateMessageRequestAuthor, error) {
	switch s {
	case "user":
		return CreateMessageRequestAuthorUser, nil
	case "assistant":
		return CreateMessageRequestAuthorAssistant, nil
	case "system":
		return CreateMessageRequestAuthorSystem, nil
	}
	var t CreateMessageRequestAuthor
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateMessageRequestAuthor) Ptr() *CreateMessageRequestAuthor {
	return &c
}
