// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/lawrencexu/funcate-server-go-sdk/internal"
	big "math/big"
)

var (
	createRecordBodyFieldLitedbSlug = big.NewInt(1 << 0)
	createRecordBodyFieldTableID    = big.NewInt(1 << 1)
	createRecordBodyFieldFields     = big.NewInt(1 << 2)
)

type CreateRecordBody struct {
	// Slug of the LiteDB service
	LitedbSlug string `json:"-" url:"-"`
	// Name of the table (views are not supported for create operations).
	TableID string `json:"-" url:"-"`
	// Comma separated string of the fields to return in the JSON response (by default returns all fields). Ex.:?fields=*
	Fields *string             `json:"-" url:"fields,omitempty"`
	Body   CreateRecordRequest `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateRecordBody) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetLitedbSlug sets the LitedbSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateRecordBody) SetLitedbSlug(litedbSlug string) {
	c.LitedbSlug = litedbSlug
	c.require(createRecordBodyFieldLitedbSlug)
}

// SetTableID sets the TableID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateRecordBody) SetTableID(tableID string) {
	c.TableID = tableID
	c.require(createRecordBodyFieldTableID)
}

// SetFields sets the Fields field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateRecordBody) SetFields(fields *string) {
	c.Fields = fields
	c.require(createRecordBodyFieldFields)
}

func (c *CreateRecordBody) UnmarshalJSON(data []byte) error {
	var body CreateRecordRequest
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	c.Body = body
	return nil
}

func (c *CreateRecordBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.Body)
}

var (
	deleteRecordRequestFieldLitedbSlug = big.NewInt(1 << 0)
	deleteRecordRequestFieldTableID    = big.NewInt(1 << 1)
	deleteRecordRequestFieldRecordID   = big.NewInt(1 << 2)
)

type DeleteRecordRequest struct {
	// Slug of the LiteDB service
	LitedbSlug string `json:"-" url:"-"`
	// Name of the table (views are not supported for delete operations).
	TableID string `json:"-" url:"-"`
	// ID of the record to delete.
	RecordID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteRecordRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetLitedbSlug sets the LitedbSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteRecordRequest) SetLitedbSlug(litedbSlug string) {
	d.LitedbSlug = litedbSlug
	d.require(deleteRecordRequestFieldLitedbSlug)
}

// SetTableID sets the TableID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteRecordRequest) SetTableID(tableID string) {
	d.TableID = tableID
	d.require(deleteRecordRequestFieldTableID)
}

// SetRecordID sets the RecordID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteRecordRequest) SetRecordID(recordID string) {
	d.RecordID = recordID
	d.require(deleteRecordRequestFieldRecordID)
}

var (
	getRecordRequestFieldLitedbSlug = big.NewInt(1 << 0)
	getRecordRequestFieldTableID    = big.NewInt(1 << 1)
	getRecordRequestFieldRecordID   = big.NewInt(1 << 2)
	getRecordRequestFieldFields     = big.NewInt(1 << 3)
)

type GetRecordRequest struct {
	// Slug of the LiteDB service
	LitedbSlug string `json:"-" url:"-"`
	// Name of the table or view. For views, only list and get operations are supported.
	TableID string `json:"-" url:"-"`
	// ID of the record to retrieve.
	RecordID string `json:"-" url:"-"`
	// Comma separated string of the fields to return in the JSON response (by default returns all fields). Ex.:?fields=*
	Fields *string `json:"-" url:"fields,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetRecordRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetLitedbSlug sets the LitedbSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetRecordRequest) SetLitedbSlug(litedbSlug string) {
	g.LitedbSlug = litedbSlug
	g.require(getRecordRequestFieldLitedbSlug)
}

// SetTableID sets the TableID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetRecordRequest) SetTableID(tableID string) {
	g.TableID = tableID
	g.require(getRecordRequestFieldTableID)
}

// SetRecordID sets the RecordID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetRecordRequest) SetRecordID(recordID string) {
	g.RecordID = recordID
	g.require(getRecordRequestFieldRecordID)
}

// SetFields sets the Fields field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetRecordRequest) SetFields(fields *string) {
	g.Fields = fields
	g.require(getRecordRequestFieldFields)
}

var (
	listRecordsRequestFieldLitedbSlug = big.NewInt(1 << 0)
	listRecordsRequestFieldTableID    = big.NewInt(1 << 1)
	listRecordsRequestFieldPage       = big.NewInt(1 << 2)
	listRecordsRequestFieldPerPage    = big.NewInt(1 << 3)
	listRecordsRequestFieldSort       = big.NewInt(1 << 4)
	listRecordsRequestFieldFilter     = big.NewInt(1 << 5)
	listRecordsRequestFieldFields     = big.NewInt(1 << 6)
)

type ListRecordsRequest struct {
	// Slug of the LiteDB service
	LitedbSlug string `json:"-" url:"-"`
	// Name of the table or view. For views, only list and get operations are supported.
	TableID string `json:"-" url:"-"`
	// The page (aka. offset) of the paginated list (default to 1).
	Page *int `json:"-" url:"page,omitempty"`
	// The max returned records per page (default to 30).
	PerPage *int `json:"-" url:"perPage,omitempty"`
	// Specify the ORDER BY fields. Add - / + (default) in front of the attribute for DESC / ASC order, e.g.: // DESC by created and ASC by id ?sort=-created,id
	Sort *string `json:"-" url:"sort,omitempty"`
	// Filter expression to filter/search the returned records list, e.g.: ?filter=(title~'abc' && created>'2022-01-01')
	// The syntax basically follows the format OPERAND OPERATOR OPERAND, where: OPERAND - could be any field literal, string (single or double quoted), number, null, true, false OPERATOR - is one of: = Equal != NOT equal > Greater than >= Greater than or equal < Less than <= Less than or equal To group and combine several expressions you can use parenthesis (...), && (AND) and || (OR) tokens. Single line comments are also supported: // Example comment.
	Filter *string `json:"-" url:"filter,omitempty"`
	// Comma separated string of the fields to return in the JSON response (by default returns all fields). Ex.:?fields=*
	Fields *string `json:"-" url:"fields,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListRecordsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetLitedbSlug sets the LitedbSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRecordsRequest) SetLitedbSlug(litedbSlug string) {
	l.LitedbSlug = litedbSlug
	l.require(listRecordsRequestFieldLitedbSlug)
}

// SetTableID sets the TableID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRecordsRequest) SetTableID(tableID string) {
	l.TableID = tableID
	l.require(listRecordsRequestFieldTableID)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRecordsRequest) SetPage(page *int) {
	l.Page = page
	l.require(listRecordsRequestFieldPage)
}

// SetPerPage sets the PerPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRecordsRequest) SetPerPage(perPage *int) {
	l.PerPage = perPage
	l.require(listRecordsRequestFieldPerPage)
}

// SetSort sets the Sort field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRecordsRequest) SetSort(sort *string) {
	l.Sort = sort
	l.require(listRecordsRequestFieldSort)
}

// SetFilter sets the Filter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRecordsRequest) SetFilter(filter *string) {
	l.Filter = filter
	l.require(listRecordsRequestFieldFilter)
}

// SetFields sets the Fields field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRecordsRequest) SetFields(fields *string) {
	l.Fields = fields
	l.require(listRecordsRequestFieldFields)
}

type CreateRecordRequest = map[string]any

var (
	getRecordResponseFieldData    = big.NewInt(1 << 0)
	getRecordResponseFieldStatus  = big.NewInt(1 << 1)
	getRecordResponseFieldCode    = big.NewInt(1 << 2)
	getRecordResponseFieldMessage = big.NewInt(1 << 3)
	getRecordResponseFieldDetails = big.NewInt(1 << 4)
)

type GetRecordResponse struct {
	Data *Record `json:"data,omitempty" url:"data,omitempty"`
	// HTTP status code
	Status int `json:"status" url:"status"`
	// General or specific code for the status, general like ok for 200, not_found for 404, specific like invalid_slug for 400
	Code string `json:"code" url:"code"`
	// Message to explain the status and code
	Message string         `json:"message" url:"message"`
	Details map[string]any `json:"details,omitempty" url:"details,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetRecordResponse) GetData() *Record {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetRecordResponse) GetStatus() int {
	if g == nil {
		return 0
	}
	return g.Status
}

func (g *GetRecordResponse) GetCode() string {
	if g == nil {
		return ""
	}
	return g.Code
}

func (g *GetRecordResponse) GetMessage() string {
	if g == nil {
		return ""
	}
	return g.Message
}

func (g *GetRecordResponse) GetDetails() map[string]any {
	if g == nil {
		return nil
	}
	return g.Details
}

func (g *GetRecordResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetRecordResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetRecordResponse) SetData(data *Record) {
	g.Data = data
	g.require(getRecordResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetRecordResponse) SetStatus(status int) {
	g.Status = status
	g.require(getRecordResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetRecordResponse) SetCode(code string) {
	g.Code = code
	g.require(getRecordResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetRecordResponse) SetMessage(message string) {
	g.Message = message
	g.require(getRecordResponseFieldMessage)
}

// SetDetails sets the Details field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetRecordResponse) SetDetails(details map[string]any) {
	g.Details = details
	g.require(getRecordResponseFieldDetails)
}

func (g *GetRecordResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetRecordResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetRecordResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetRecordResponse) MarshalJSON() ([]byte, error) {
	type embed GetRecordResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetRecordResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	listRecordsResponseFieldData    = big.NewInt(1 << 0)
	listRecordsResponseFieldStatus  = big.NewInt(1 << 1)
	listRecordsResponseFieldCode    = big.NewInt(1 << 2)
	listRecordsResponseFieldMessage = big.NewInt(1 << 3)
	listRecordsResponseFieldDetails = big.NewInt(1 << 4)
)

type ListRecordsResponse struct {
	Data *ListRecordsResponseData `json:"data,omitempty" url:"data,omitempty"`
	// HTTP status code
	Status int `json:"status" url:"status"`
	// General or specific code for the status, general like ok for 200, not_found for 404, specific like invalid_slug for 400
	Code string `json:"code" url:"code"`
	// Message to explain the status and code
	Message string         `json:"message" url:"message"`
	Details map[string]any `json:"details,omitempty" url:"details,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListRecordsResponse) GetData() *ListRecordsResponseData {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListRecordsResponse) GetStatus() int {
	if l == nil {
		return 0
	}
	return l.Status
}

func (l *ListRecordsResponse) GetCode() string {
	if l == nil {
		return ""
	}
	return l.Code
}

func (l *ListRecordsResponse) GetMessage() string {
	if l == nil {
		return ""
	}
	return l.Message
}

func (l *ListRecordsResponse) GetDetails() map[string]any {
	if l == nil {
		return nil
	}
	return l.Details
}

func (l *ListRecordsResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListRecordsResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRecordsResponse) SetData(data *ListRecordsResponseData) {
	l.Data = data
	l.require(listRecordsResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRecordsResponse) SetStatus(status int) {
	l.Status = status
	l.require(listRecordsResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRecordsResponse) SetCode(code string) {
	l.Code = code
	l.require(listRecordsResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRecordsResponse) SetMessage(message string) {
	l.Message = message
	l.require(listRecordsResponseFieldMessage)
}

// SetDetails sets the Details field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRecordsResponse) SetDetails(details map[string]any) {
	l.Details = details
	l.require(listRecordsResponseFieldDetails)
}

func (l *ListRecordsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListRecordsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListRecordsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListRecordsResponse) MarshalJSON() ([]byte, error) {
	type embed ListRecordsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListRecordsResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	listRecordsResponseDataFieldPage       = big.NewInt(1 << 0)
	listRecordsResponseDataFieldPerPage    = big.NewInt(1 << 1)
	listRecordsResponseDataFieldTotalItems = big.NewInt(1 << 2)
	listRecordsResponseDataFieldTotalPages = big.NewInt(1 << 3)
	listRecordsResponseDataFieldItems      = big.NewInt(1 << 4)
)

type ListRecordsResponseData struct {
	Page       *int     `json:"page,omitempty" url:"page,omitempty"`
	PerPage    *int     `json:"perPage,omitempty" url:"perPage,omitempty"`
	TotalItems *int     `json:"totalItems,omitempty" url:"totalItems,omitempty"`
	TotalPages *int     `json:"totalPages,omitempty" url:"totalPages,omitempty"`
	Items      []Record `json:"items,omitempty" url:"items,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListRecordsResponseData) GetPage() *int {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListRecordsResponseData) GetPerPage() *int {
	if l == nil {
		return nil
	}
	return l.PerPage
}

func (l *ListRecordsResponseData) GetTotalItems() *int {
	if l == nil {
		return nil
	}
	return l.TotalItems
}

func (l *ListRecordsResponseData) GetTotalPages() *int {
	if l == nil {
		return nil
	}
	return l.TotalPages
}

func (l *ListRecordsResponseData) GetItems() []Record {
	if l == nil {
		return nil
	}
	return l.Items
}

func (l *ListRecordsResponseData) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListRecordsResponseData) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRecordsResponseData) SetPage(page *int) {
	l.Page = page
	l.require(listRecordsResponseDataFieldPage)
}

// SetPerPage sets the PerPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRecordsResponseData) SetPerPage(perPage *int) {
	l.PerPage = perPage
	l.require(listRecordsResponseDataFieldPerPage)
}

// SetTotalItems sets the TotalItems field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRecordsResponseData) SetTotalItems(totalItems *int) {
	l.TotalItems = totalItems
	l.require(listRecordsResponseDataFieldTotalItems)
}

// SetTotalPages sets the TotalPages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRecordsResponseData) SetTotalPages(totalPages *int) {
	l.TotalPages = totalPages
	l.require(listRecordsResponseDataFieldTotalPages)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRecordsResponseData) SetItems(items []Record) {
	l.Items = items
	l.require(listRecordsResponseDataFieldItems)
}

func (l *ListRecordsResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler ListRecordsResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListRecordsResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListRecordsResponseData) MarshalJSON() ([]byte, error) {
	type embed ListRecordsResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListRecordsResponseData) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

type Record = map[string]any

type UpdateRecordRequest = map[string]any

var (
	updateRecordBodyFieldLitedbSlug = big.NewInt(1 << 0)
	updateRecordBodyFieldTableID    = big.NewInt(1 << 1)
	updateRecordBodyFieldRecordID   = big.NewInt(1 << 2)
	updateRecordBodyFieldFields     = big.NewInt(1 << 3)
)

type UpdateRecordBody struct {
	// Slug of the LiteDB service
	LitedbSlug string `json:"-" url:"-"`
	// Name of the table (views are not supported for update operations).
	TableID string `json:"-" url:"-"`
	// ID of the record to update.
	RecordID string `json:"-" url:"-"`
	// Comma separated string of the fields to return in the JSON response (by default returns all fields). Ex.: ?fields=*
	Fields *string             `json:"-" url:"fields,omitempty"`
	Body   UpdateRecordRequest `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateRecordBody) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetLitedbSlug sets the LitedbSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateRecordBody) SetLitedbSlug(litedbSlug string) {
	u.LitedbSlug = litedbSlug
	u.require(updateRecordBodyFieldLitedbSlug)
}

// SetTableID sets the TableID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateRecordBody) SetTableID(tableID string) {
	u.TableID = tableID
	u.require(updateRecordBodyFieldTableID)
}

// SetRecordID sets the RecordID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateRecordBody) SetRecordID(recordID string) {
	u.RecordID = recordID
	u.require(updateRecordBodyFieldRecordID)
}

// SetFields sets the Fields field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateRecordBody) SetFields(fields *string) {
	u.Fields = fields
	u.require(updateRecordBodyFieldFields)
}

func (u *UpdateRecordBody) UnmarshalJSON(data []byte) error {
	var body UpdateRecordRequest
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.Body = body
	return nil
}

func (u *UpdateRecordBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}
