// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/lawrencexu/funcate-server-go-sdk/internal"
	big "math/big"
)

var (
	createSessionRequestFieldAgentSlug = big.NewInt(1 << 0)
	createSessionRequestFieldOwnerID   = big.NewInt(1 << 1)
)

type CreateSessionRequest struct {
	// Agent slug defined in funcate.yaml
	AgentSlug string `json:"-" url:"-"`
	// Owner identifier
	OwnerID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateSessionRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAgentSlug sets the AgentSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSessionRequest) SetAgentSlug(agentSlug string) {
	c.AgentSlug = agentSlug
	c.require(createSessionRequestFieldAgentSlug)
}

// SetOwnerID sets the OwnerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSessionRequest) SetOwnerID(ownerID string) {
	c.OwnerID = ownerID
	c.require(createSessionRequestFieldOwnerID)
}

var (
	deleteSessionRequestFieldAgentSlug = big.NewInt(1 << 0)
	deleteSessionRequestFieldOwnerID   = big.NewInt(1 << 1)
	deleteSessionRequestFieldSessionID = big.NewInt(1 << 2)
)

type DeleteSessionRequest struct {
	// Agent slug defined in funcate.yaml
	AgentSlug string `json:"-" url:"-"`
	// Owner identifier
	OwnerID string `json:"-" url:"-"`
	// Session identifier
	SessionID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteSessionRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetAgentSlug sets the AgentSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteSessionRequest) SetAgentSlug(agentSlug string) {
	d.AgentSlug = agentSlug
	d.require(deleteSessionRequestFieldAgentSlug)
}

// SetOwnerID sets the OwnerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteSessionRequest) SetOwnerID(ownerID string) {
	d.OwnerID = ownerID
	d.require(deleteSessionRequestFieldOwnerID)
}

// SetSessionID sets the SessionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteSessionRequest) SetSessionID(sessionID string) {
	d.SessionID = sessionID
	d.require(deleteSessionRequestFieldSessionID)
}

var (
	getSessionRequestFieldAgentSlug = big.NewInt(1 << 0)
	getSessionRequestFieldOwnerID   = big.NewInt(1 << 1)
	getSessionRequestFieldSessionID = big.NewInt(1 << 2)
)

type GetSessionRequest struct {
	// Agent slug defined in funcate.yaml
	AgentSlug string `json:"-" url:"-"`
	// Owner identifier
	OwnerID string `json:"-" url:"-"`
	// Session identifier
	SessionID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetSessionRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetAgentSlug sets the AgentSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSessionRequest) SetAgentSlug(agentSlug string) {
	g.AgentSlug = agentSlug
	g.require(getSessionRequestFieldAgentSlug)
}

// SetOwnerID sets the OwnerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSessionRequest) SetOwnerID(ownerID string) {
	g.OwnerID = ownerID
	g.require(getSessionRequestFieldOwnerID)
}

// SetSessionID sets the SessionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSessionRequest) SetSessionID(sessionID string) {
	g.SessionID = sessionID
	g.require(getSessionRequestFieldSessionID)
}

var (
	listSessionsRequestFieldAgentSlug = big.NewInt(1 << 0)
	listSessionsRequestFieldOwnerID   = big.NewInt(1 << 1)
	listSessionsRequestFieldPage      = big.NewInt(1 << 2)
	listSessionsRequestFieldPerPage   = big.NewInt(1 << 3)
	listSessionsRequestFieldSort      = big.NewInt(1 << 4)
	listSessionsRequestFieldFilter    = big.NewInt(1 << 5)
	listSessionsRequestFieldFields    = big.NewInt(1 << 6)
)

type ListSessionsRequest struct {
	// Agent slug defined in funcate.yaml
	AgentSlug string `json:"-" url:"-"`
	// Owner identifier
	OwnerID string `json:"-" url:"-"`
	// The page (aka. offset) of the paginated list (default to 1).
	Page *int `json:"-" url:"page,omitempty"`
	// The max returned sessions per page (default to 30).
	PerPage *int `json:"-" url:"perPage,omitempty"`
	// Specify the ORDER BY fields. Add - / + (default) in front of the attribute for DESC / ASC order, e.g.: // DESC by created and ASC by name ?sort=-created_at
	Sort *string `json:"-" url:"sort,omitempty"`
	// Filter expression to filter/search the returned sessions list, e.g.: ?filter=(created_at>1732924800000)
	// The syntax basically follows the format OPERAND OPERATOR OPERAND, where: OPERAND - could be any field literal, string (single or double quoted), number, null, true, false OPERATOR - is one of: = Equal != NOT equal > Greater than >= Greater than or equal < Less than <= Less than or equal ~ Contains (for strings) !~ NOT contains (for strings) To group and combine several expressions you can use parenthesis (...), && (AND) and || (OR) tokens. Single line comments are also supported: // Example comment.
	Filter *string `json:"-" url:"filter,omitempty"`
	// Comma separated string of the fields to return in the JSON response (by default returns all fields). Ex.:?fields=id,agent_slug,owner_id,created_at
	Fields *string `json:"-" url:"fields,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListSessionsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetAgentSlug sets the AgentSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsRequest) SetAgentSlug(agentSlug string) {
	l.AgentSlug = agentSlug
	l.require(listSessionsRequestFieldAgentSlug)
}

// SetOwnerID sets the OwnerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsRequest) SetOwnerID(ownerID string) {
	l.OwnerID = ownerID
	l.require(listSessionsRequestFieldOwnerID)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsRequest) SetPage(page *int) {
	l.Page = page
	l.require(listSessionsRequestFieldPage)
}

// SetPerPage sets the PerPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsRequest) SetPerPage(perPage *int) {
	l.PerPage = perPage
	l.require(listSessionsRequestFieldPerPage)
}

// SetSort sets the Sort field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsRequest) SetSort(sort *string) {
	l.Sort = sort
	l.require(listSessionsRequestFieldSort)
}

// SetFilter sets the Filter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsRequest) SetFilter(filter *string) {
	l.Filter = filter
	l.require(listSessionsRequestFieldFilter)
}

// SetFields sets the Fields field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsRequest) SetFields(fields *string) {
	l.Fields = fields
	l.require(listSessionsRequestFieldFields)
}

var (
	createSessionResponseFieldData    = big.NewInt(1 << 0)
	createSessionResponseFieldStatus  = big.NewInt(1 << 1)
	createSessionResponseFieldCode    = big.NewInt(1 << 2)
	createSessionResponseFieldMessage = big.NewInt(1 << 3)
	createSessionResponseFieldDetails = big.NewInt(1 << 4)
)

type CreateSessionResponse struct {
	Data *CreateSessionResponseData `json:"data,omitempty" url:"data,omitempty"`
	// HTTP status code
	Status int `json:"status" url:"status"`
	// General or specific code for the status, general like ok for 200, not_found for 404, specific like invalid_slug for 400
	Code string `json:"code" url:"code"`
	// Message to explain the status and code
	Message string         `json:"message" url:"message"`
	Details map[string]any `json:"details,omitempty" url:"details,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateSessionResponse) GetData() *CreateSessionResponseData {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *CreateSessionResponse) GetStatus() int {
	if c == nil {
		return 0
	}
	return c.Status
}

func (c *CreateSessionResponse) GetCode() string {
	if c == nil {
		return ""
	}
	return c.Code
}

func (c *CreateSessionResponse) GetMessage() string {
	if c == nil {
		return ""
	}
	return c.Message
}

func (c *CreateSessionResponse) GetDetails() map[string]any {
	if c == nil {
		return nil
	}
	return c.Details
}

func (c *CreateSessionResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateSessionResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSessionResponse) SetData(data *CreateSessionResponseData) {
	c.Data = data
	c.require(createSessionResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSessionResponse) SetStatus(status int) {
	c.Status = status
	c.require(createSessionResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSessionResponse) SetCode(code string) {
	c.Code = code
	c.require(createSessionResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSessionResponse) SetMessage(message string) {
	c.Message = message
	c.require(createSessionResponseFieldMessage)
}

// SetDetails sets the Details field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSessionResponse) SetDetails(details map[string]any) {
	c.Details = details
	c.require(createSessionResponseFieldDetails)
}

func (c *CreateSessionResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateSessionResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateSessionResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateSessionResponse) MarshalJSON() ([]byte, error) {
	type embed CreateSessionResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateSessionResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	createSessionResponseDataFieldSession = big.NewInt(1 << 0)
)

type CreateSessionResponseData struct {
	Session *Session `json:"session" url:"session"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateSessionResponseData) GetSession() *Session {
	if c == nil {
		return nil
	}
	return c.Session
}

func (c *CreateSessionResponseData) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateSessionResponseData) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetSession sets the Session field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSessionResponseData) SetSession(session *Session) {
	c.Session = session
	c.require(createSessionResponseDataFieldSession)
}

func (c *CreateSessionResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateSessionResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateSessionResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateSessionResponseData) MarshalJSON() ([]byte, error) {
	type embed CreateSessionResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateSessionResponseData) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	deleteSessionResponseFieldData    = big.NewInt(1 << 0)
	deleteSessionResponseFieldStatus  = big.NewInt(1 << 1)
	deleteSessionResponseFieldCode    = big.NewInt(1 << 2)
	deleteSessionResponseFieldMessage = big.NewInt(1 << 3)
	deleteSessionResponseFieldDetails = big.NewInt(1 << 4)
)

type DeleteSessionResponse struct {
	Data map[string]any `json:"data,omitempty" url:"data,omitempty"`
	// HTTP status code
	Status int `json:"status" url:"status"`
	// General or specific code for the status, general like ok for 200, not_found for 404, specific like invalid_slug for 400
	Code string `json:"code" url:"code"`
	// Message to explain the status and code
	Message string         `json:"message" url:"message"`
	Details map[string]any `json:"details,omitempty" url:"details,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeleteSessionResponse) GetData() map[string]any {
	if d == nil {
		return nil
	}
	return d.Data
}

func (d *DeleteSessionResponse) GetStatus() int {
	if d == nil {
		return 0
	}
	return d.Status
}

func (d *DeleteSessionResponse) GetCode() string {
	if d == nil {
		return ""
	}
	return d.Code
}

func (d *DeleteSessionResponse) GetMessage() string {
	if d == nil {
		return ""
	}
	return d.Message
}

func (d *DeleteSessionResponse) GetDetails() map[string]any {
	if d == nil {
		return nil
	}
	return d.Details
}

func (d *DeleteSessionResponse) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeleteSessionResponse) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteSessionResponse) SetData(data map[string]any) {
	d.Data = data
	d.require(deleteSessionResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteSessionResponse) SetStatus(status int) {
	d.Status = status
	d.require(deleteSessionResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteSessionResponse) SetCode(code string) {
	d.Code = code
	d.require(deleteSessionResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteSessionResponse) SetMessage(message string) {
	d.Message = message
	d.require(deleteSessionResponseFieldMessage)
}

// SetDetails sets the Details field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteSessionResponse) SetDetails(details map[string]any) {
	d.Details = details
	d.require(deleteSessionResponseFieldDetails)
}

func (d *DeleteSessionResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteSessionResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteSessionResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteSessionResponse) MarshalJSON() ([]byte, error) {
	type embed DeleteSessionResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeleteSessionResponse) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	getSessionResponseFieldData    = big.NewInt(1 << 0)
	getSessionResponseFieldStatus  = big.NewInt(1 << 1)
	getSessionResponseFieldCode    = big.NewInt(1 << 2)
	getSessionResponseFieldMessage = big.NewInt(1 << 3)
	getSessionResponseFieldDetails = big.NewInt(1 << 4)
)

type GetSessionResponse struct {
	Data *GetSessionResponseData `json:"data,omitempty" url:"data,omitempty"`
	// HTTP status code
	Status int `json:"status" url:"status"`
	// General or specific code for the status, general like ok for 200, not_found for 404, specific like invalid_slug for 400
	Code string `json:"code" url:"code"`
	// Message to explain the status and code
	Message string         `json:"message" url:"message"`
	Details map[string]any `json:"details,omitempty" url:"details,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetSessionResponse) GetData() *GetSessionResponseData {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetSessionResponse) GetStatus() int {
	if g == nil {
		return 0
	}
	return g.Status
}

func (g *GetSessionResponse) GetCode() string {
	if g == nil {
		return ""
	}
	return g.Code
}

func (g *GetSessionResponse) GetMessage() string {
	if g == nil {
		return ""
	}
	return g.Message
}

func (g *GetSessionResponse) GetDetails() map[string]any {
	if g == nil {
		return nil
	}
	return g.Details
}

func (g *GetSessionResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetSessionResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSessionResponse) SetData(data *GetSessionResponseData) {
	g.Data = data
	g.require(getSessionResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSessionResponse) SetStatus(status int) {
	g.Status = status
	g.require(getSessionResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSessionResponse) SetCode(code string) {
	g.Code = code
	g.require(getSessionResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSessionResponse) SetMessage(message string) {
	g.Message = message
	g.require(getSessionResponseFieldMessage)
}

// SetDetails sets the Details field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSessionResponse) SetDetails(details map[string]any) {
	g.Details = details
	g.require(getSessionResponseFieldDetails)
}

func (g *GetSessionResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetSessionResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetSessionResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetSessionResponse) MarshalJSON() ([]byte, error) {
	type embed GetSessionResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetSessionResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getSessionResponseDataFieldSession = big.NewInt(1 << 0)
)

type GetSessionResponseData struct {
	Session *Session `json:"session" url:"session"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetSessionResponseData) GetSession() *Session {
	if g == nil {
		return nil
	}
	return g.Session
}

func (g *GetSessionResponseData) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetSessionResponseData) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetSession sets the Session field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSessionResponseData) SetSession(session *Session) {
	g.Session = session
	g.require(getSessionResponseDataFieldSession)
}

func (g *GetSessionResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler GetSessionResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetSessionResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetSessionResponseData) MarshalJSON() ([]byte, error) {
	type embed GetSessionResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetSessionResponseData) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	listSessionsResponseFieldData    = big.NewInt(1 << 0)
	listSessionsResponseFieldStatus  = big.NewInt(1 << 1)
	listSessionsResponseFieldCode    = big.NewInt(1 << 2)
	listSessionsResponseFieldMessage = big.NewInt(1 << 3)
	listSessionsResponseFieldDetails = big.NewInt(1 << 4)
)

type ListSessionsResponse struct {
	Data *ListSessionsResponseData `json:"data,omitempty" url:"data,omitempty"`
	// HTTP status code
	Status int `json:"status" url:"status"`
	// General or specific code for the status, general like ok for 200, not_found for 404, specific like invalid_slug for 400
	Code string `json:"code" url:"code"`
	// Message to explain the status and code
	Message string         `json:"message" url:"message"`
	Details map[string]any `json:"details,omitempty" url:"details,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListSessionsResponse) GetData() *ListSessionsResponseData {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListSessionsResponse) GetStatus() int {
	if l == nil {
		return 0
	}
	return l.Status
}

func (l *ListSessionsResponse) GetCode() string {
	if l == nil {
		return ""
	}
	return l.Code
}

func (l *ListSessionsResponse) GetMessage() string {
	if l == nil {
		return ""
	}
	return l.Message
}

func (l *ListSessionsResponse) GetDetails() map[string]any {
	if l == nil {
		return nil
	}
	return l.Details
}

func (l *ListSessionsResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListSessionsResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsResponse) SetData(data *ListSessionsResponseData) {
	l.Data = data
	l.require(listSessionsResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsResponse) SetStatus(status int) {
	l.Status = status
	l.require(listSessionsResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsResponse) SetCode(code string) {
	l.Code = code
	l.require(listSessionsResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsResponse) SetMessage(message string) {
	l.Message = message
	l.require(listSessionsResponseFieldMessage)
}

// SetDetails sets the Details field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsResponse) SetDetails(details map[string]any) {
	l.Details = details
	l.require(listSessionsResponseFieldDetails)
}

func (l *ListSessionsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListSessionsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListSessionsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListSessionsResponse) MarshalJSON() ([]byte, error) {
	type embed ListSessionsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListSessionsResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	listSessionsResponseDataFieldItems      = big.NewInt(1 << 0)
	listSessionsResponseDataFieldPage       = big.NewInt(1 << 1)
	listSessionsResponseDataFieldPerPage    = big.NewInt(1 << 2)
	listSessionsResponseDataFieldTotalItems = big.NewInt(1 << 3)
	listSessionsResponseDataFieldTotalPages = big.NewInt(1 << 4)
)

type ListSessionsResponseData struct {
	Items []*Session `json:"items" url:"items"`
	// Current page number
	Page int `json:"page" url:"page"`
	// Items per page
	PerPage int `json:"perPage" url:"perPage"`
	// total number of items
	TotalItems int `json:"totalItems" url:"totalItems"`
	// Total number of pages
	TotalPages int `json:"totalPages" url:"totalPages"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListSessionsResponseData) GetItems() []*Session {
	if l == nil {
		return nil
	}
	return l.Items
}

func (l *ListSessionsResponseData) GetPage() int {
	if l == nil {
		return 0
	}
	return l.Page
}

func (l *ListSessionsResponseData) GetPerPage() int {
	if l == nil {
		return 0
	}
	return l.PerPage
}

func (l *ListSessionsResponseData) GetTotalItems() int {
	if l == nil {
		return 0
	}
	return l.TotalItems
}

func (l *ListSessionsResponseData) GetTotalPages() int {
	if l == nil {
		return 0
	}
	return l.TotalPages
}

func (l *ListSessionsResponseData) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListSessionsResponseData) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsResponseData) SetItems(items []*Session) {
	l.Items = items
	l.require(listSessionsResponseDataFieldItems)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsResponseData) SetPage(page int) {
	l.Page = page
	l.require(listSessionsResponseDataFieldPage)
}

// SetPerPage sets the PerPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsResponseData) SetPerPage(perPage int) {
	l.PerPage = perPage
	l.require(listSessionsResponseDataFieldPerPage)
}

// SetTotalItems sets the TotalItems field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsResponseData) SetTotalItems(totalItems int) {
	l.TotalItems = totalItems
	l.require(listSessionsResponseDataFieldTotalItems)
}

// SetTotalPages sets the TotalPages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSessionsResponseData) SetTotalPages(totalPages int) {
	l.TotalPages = totalPages
	l.require(listSessionsResponseDataFieldTotalPages)
}

func (l *ListSessionsResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler ListSessionsResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListSessionsResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListSessionsResponseData) MarshalJSON() ([]byte, error) {
	type embed ListSessionsResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListSessionsResponseData) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	sessionFieldID        = big.NewInt(1 << 0)
	sessionFieldAgentSlug = big.NewInt(1 << 1)
	sessionFieldOwnerID   = big.NewInt(1 << 2)
	sessionFieldCreatedAt = big.NewInt(1 << 3)
	sessionFieldUpdatedAt = big.NewInt(1 << 4)
)

type Session struct {
	// Unique session identifier
	ID string `json:"id" url:"id"`
	// Agent slug
	AgentSlug string `json:"agent_slug" url:"agent_slug"`
	// Owner identifier
	OwnerID string `json:"owner_id" url:"owner_id"`
	// Creation timestamp in milliseconds since epoch
	CreatedAt int64 `json:"created_at" url:"created_at"`
	// Last update timestamp in milliseconds since epoch
	UpdatedAt int64 `json:"updated_at" url:"updated_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *Session) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *Session) GetAgentSlug() string {
	if s == nil {
		return ""
	}
	return s.AgentSlug
}

func (s *Session) GetOwnerID() string {
	if s == nil {
		return ""
	}
	return s.OwnerID
}

func (s *Session) GetCreatedAt() int64 {
	if s == nil {
		return 0
	}
	return s.CreatedAt
}

func (s *Session) GetUpdatedAt() int64 {
	if s == nil {
		return 0
	}
	return s.UpdatedAt
}

func (s *Session) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *Session) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Session) SetID(id string) {
	s.ID = id
	s.require(sessionFieldID)
}

// SetAgentSlug sets the AgentSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Session) SetAgentSlug(agentSlug string) {
	s.AgentSlug = agentSlug
	s.require(sessionFieldAgentSlug)
}

// SetOwnerID sets the OwnerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Session) SetOwnerID(ownerID string) {
	s.OwnerID = ownerID
	s.require(sessionFieldOwnerID)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Session) SetCreatedAt(createdAt int64) {
	s.CreatedAt = createdAt
	s.require(sessionFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Session) SetUpdatedAt(updatedAt int64) {
	s.UpdatedAt = updatedAt
	s.require(sessionFieldUpdatedAt)
}

func (s *Session) UnmarshalJSON(data []byte) error {
	type unmarshaler Session
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = Session(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *Session) MarshalJSON() ([]byte, error) {
	type embed Session
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *Session) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}
