// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/lawrencexu/funcate-server-go-sdk/internal"
	big "math/big"
	time "time"
)

var (
	standardResponseFieldStatus  = big.NewInt(1 << 0)
	standardResponseFieldCode    = big.NewInt(1 << 1)
	standardResponseFieldMessage = big.NewInt(1 << 2)
	standardResponseFieldData    = big.NewInt(1 << 3)
	standardResponseFieldDetails = big.NewInt(1 << 4)
)

type StandardResponse struct {
	// HTTP status code
	Status int `json:"status" url:"status"`
	// General or specific code for the status, general like ok for 200, not_found for 404, specific like invalid_slug for 400
	Code string `json:"code" url:"code"`
	// Message to explain the status and code
	Message string         `json:"message" url:"message"`
	Data    map[string]any `json:"data,omitempty" url:"data,omitempty"`
	Details map[string]any `json:"details,omitempty" url:"details,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *StandardResponse) GetStatus() int {
	if s == nil {
		return 0
	}
	return s.Status
}

func (s *StandardResponse) GetCode() string {
	if s == nil {
		return ""
	}
	return s.Code
}

func (s *StandardResponse) GetMessage() string {
	if s == nil {
		return ""
	}
	return s.Message
}

func (s *StandardResponse) GetData() map[string]any {
	if s == nil {
		return nil
	}
	return s.Data
}

func (s *StandardResponse) GetDetails() map[string]any {
	if s == nil {
		return nil
	}
	return s.Details
}

func (s *StandardResponse) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *StandardResponse) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StandardResponse) SetStatus(status int) {
	s.Status = status
	s.require(standardResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StandardResponse) SetCode(code string) {
	s.Code = code
	s.require(standardResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StandardResponse) SetMessage(message string) {
	s.Message = message
	s.require(standardResponseFieldMessage)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StandardResponse) SetData(data map[string]any) {
	s.Data = data
	s.require(standardResponseFieldData)
}

// SetDetails sets the Details field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StandardResponse) SetDetails(details map[string]any) {
	s.Details = details
	s.require(standardResponseFieldDetails)
}

func (s *StandardResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler StandardResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = StandardResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *StandardResponse) MarshalJSON() ([]byte, error) {
	type embed StandardResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *StandardResponse) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	userFieldID        = big.NewInt(1 << 0)
	userFieldUsername  = big.NewInt(1 << 1)
	userFieldCreatedAt = big.NewInt(1 << 2)
	userFieldUpdatedAt = big.NewInt(1 << 3)
)

type User struct {
	// Unique user identifier
	ID string `json:"id" url:"id"`
	// User's username
	Username string `json:"username" url:"username"`
	// User creation timestamp
	CreatedAt time.Time `json:"createdAt" url:"createdAt"`
	// User last update timestamp
	UpdatedAt time.Time `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *User) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *User) GetUsername() string {
	if u == nil {
		return ""
	}
	return u.Username
}

func (u *User) GetCreatedAt() time.Time {
	if u == nil {
		return time.Time{}
	}
	return u.CreatedAt
}

func (u *User) GetUpdatedAt() time.Time {
	if u == nil {
		return time.Time{}
	}
	return u.UpdatedAt
}

func (u *User) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *User) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *User) SetID(id string) {
	u.ID = id
	u.require(userFieldID)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *User) SetUsername(username string) {
	u.Username = username
	u.require(userFieldUsername)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *User) SetCreatedAt(createdAt time.Time) {
	u.CreatedAt = createdAt
	u.require(userFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *User) SetUpdatedAt(updatedAt time.Time) {
	u.UpdatedAt = updatedAt
	u.require(userFieldUpdatedAt)
}

func (u *User) UnmarshalJSON(data []byte) error {
	type embed User
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed: embed(*u),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*u = User(unmarshaler.embed)
	u.CreatedAt = unmarshaler.CreatedAt.Time()
	u.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *User) MarshalJSON() ([]byte, error) {
	type embed User
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed:     embed(*u),
		CreatedAt: internal.NewDateTime(u.CreatedAt),
		UpdatedAt: internal.NewDateTime(u.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *User) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}
