// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/lawrencexu/funcate-server-go-sdk/internal"
	big "math/big"
)

var (
	createUserRequestFieldAuthSlug        = big.NewInt(1 << 0)
	createUserRequestFieldUsername        = big.NewInt(1 << 1)
	createUserRequestFieldPassword        = big.NewInt(1 << 2)
	createUserRequestFieldPasswordConfirm = big.NewInt(1 << 3)
)

type CreateUserRequest struct {
	// Auth slug defined in funcate.yaml
	AuthSlug string `json:"-" url:"-"`
	// User's username
	Username string `json:"username" url:"-"`
	// User's password
	Password string `json:"password" url:"-"`
	// Password confirmation
	PasswordConfirm string `json:"passwordConfirm" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateUserRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAuthSlug sets the AuthSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateUserRequest) SetAuthSlug(authSlug string) {
	c.AuthSlug = authSlug
	c.require(createUserRequestFieldAuthSlug)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateUserRequest) SetUsername(username string) {
	c.Username = username
	c.require(createUserRequestFieldUsername)
}

// SetPassword sets the Password field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateUserRequest) SetPassword(password string) {
	c.Password = password
	c.require(createUserRequestFieldPassword)
}

// SetPasswordConfirm sets the PasswordConfirm field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateUserRequest) SetPasswordConfirm(passwordConfirm string) {
	c.PasswordConfirm = passwordConfirm
	c.require(createUserRequestFieldPasswordConfirm)
}

func (c *CreateUserRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateUserRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateUserRequest(body)
	return nil
}

func (c *CreateUserRequest) MarshalJSON() ([]byte, error) {
	type embed CreateUserRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getCurrentUserRequestFieldAuthSlug = big.NewInt(1 << 0)
)

type GetCurrentUserRequest struct {
	// Auth slug defined in funcate.yaml
	AuthSlug string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetCurrentUserRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetAuthSlug sets the AuthSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCurrentUserRequest) SetAuthSlug(authSlug string) {
	g.AuthSlug = authSlug
	g.require(getCurrentUserRequestFieldAuthSlug)
}

var (
	createUserResponseFieldData    = big.NewInt(1 << 0)
	createUserResponseFieldStatus  = big.NewInt(1 << 1)
	createUserResponseFieldCode    = big.NewInt(1 << 2)
	createUserResponseFieldMessage = big.NewInt(1 << 3)
	createUserResponseFieldDetails = big.NewInt(1 << 4)
)

type CreateUserResponse struct {
	Data *CreateUserResponseData `json:"data,omitempty" url:"data,omitempty"`
	// HTTP status code
	Status int `json:"status" url:"status"`
	// General or specific code for the status, general like ok for 200, not_found for 404, specific like invalid_slug for 400
	Code string `json:"code" url:"code"`
	// Message to explain the status and code
	Message string         `json:"message" url:"message"`
	Details map[string]any `json:"details,omitempty" url:"details,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateUserResponse) GetData() *CreateUserResponseData {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *CreateUserResponse) GetStatus() int {
	if c == nil {
		return 0
	}
	return c.Status
}

func (c *CreateUserResponse) GetCode() string {
	if c == nil {
		return ""
	}
	return c.Code
}

func (c *CreateUserResponse) GetMessage() string {
	if c == nil {
		return ""
	}
	return c.Message
}

func (c *CreateUserResponse) GetDetails() map[string]any {
	if c == nil {
		return nil
	}
	return c.Details
}

func (c *CreateUserResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateUserResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateUserResponse) SetData(data *CreateUserResponseData) {
	c.Data = data
	c.require(createUserResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateUserResponse) SetStatus(status int) {
	c.Status = status
	c.require(createUserResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateUserResponse) SetCode(code string) {
	c.Code = code
	c.require(createUserResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateUserResponse) SetMessage(message string) {
	c.Message = message
	c.require(createUserResponseFieldMessage)
}

// SetDetails sets the Details field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateUserResponse) SetDetails(details map[string]any) {
	c.Details = details
	c.require(createUserResponseFieldDetails)
}

func (c *CreateUserResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateUserResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateUserResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateUserResponse) MarshalJSON() ([]byte, error) {
	type embed CreateUserResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateUserResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	createUserResponseDataFieldToken          = big.NewInt(1 << 0)
	createUserResponseDataFieldTokenExpiresIn = big.NewInt(1 << 1)
	createUserResponseDataFieldUser           = big.NewInt(1 << 2)
)

type CreateUserResponseData struct {
	// JWT token for authentication
	Token string `json:"token" url:"token"`
	// Token expiration time in seconds
	TokenExpiresIn int   `json:"tokenExpiresIn" url:"tokenExpiresIn"`
	User           *User `json:"user" url:"user"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateUserResponseData) GetToken() string {
	if c == nil {
		return ""
	}
	return c.Token
}

func (c *CreateUserResponseData) GetTokenExpiresIn() int {
	if c == nil {
		return 0
	}
	return c.TokenExpiresIn
}

func (c *CreateUserResponseData) GetUser() *User {
	if c == nil {
		return nil
	}
	return c.User
}

func (c *CreateUserResponseData) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateUserResponseData) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetToken sets the Token field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateUserResponseData) SetToken(token string) {
	c.Token = token
	c.require(createUserResponseDataFieldToken)
}

// SetTokenExpiresIn sets the TokenExpiresIn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateUserResponseData) SetTokenExpiresIn(tokenExpiresIn int) {
	c.TokenExpiresIn = tokenExpiresIn
	c.require(createUserResponseDataFieldTokenExpiresIn)
}

// SetUser sets the User field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateUserResponseData) SetUser(user *User) {
	c.User = user
	c.require(createUserResponseDataFieldUser)
}

func (c *CreateUserResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateUserResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateUserResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateUserResponseData) MarshalJSON() ([]byte, error) {
	type embed CreateUserResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateUserResponseData) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	getCurrentUserResponseFieldData    = big.NewInt(1 << 0)
	getCurrentUserResponseFieldStatus  = big.NewInt(1 << 1)
	getCurrentUserResponseFieldCode    = big.NewInt(1 << 2)
	getCurrentUserResponseFieldMessage = big.NewInt(1 << 3)
	getCurrentUserResponseFieldDetails = big.NewInt(1 << 4)
)

type GetCurrentUserResponse struct {
	Data *GetCurrentUserResponseData `json:"data,omitempty" url:"data,omitempty"`
	// HTTP status code
	Status int `json:"status" url:"status"`
	// General or specific code for the status, general like ok for 200, not_found for 404, specific like invalid_slug for 400
	Code string `json:"code" url:"code"`
	// Message to explain the status and code
	Message string         `json:"message" url:"message"`
	Details map[string]any `json:"details,omitempty" url:"details,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetCurrentUserResponse) GetData() *GetCurrentUserResponseData {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetCurrentUserResponse) GetStatus() int {
	if g == nil {
		return 0
	}
	return g.Status
}

func (g *GetCurrentUserResponse) GetCode() string {
	if g == nil {
		return ""
	}
	return g.Code
}

func (g *GetCurrentUserResponse) GetMessage() string {
	if g == nil {
		return ""
	}
	return g.Message
}

func (g *GetCurrentUserResponse) GetDetails() map[string]any {
	if g == nil {
		return nil
	}
	return g.Details
}

func (g *GetCurrentUserResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetCurrentUserResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCurrentUserResponse) SetData(data *GetCurrentUserResponseData) {
	g.Data = data
	g.require(getCurrentUserResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCurrentUserResponse) SetStatus(status int) {
	g.Status = status
	g.require(getCurrentUserResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCurrentUserResponse) SetCode(code string) {
	g.Code = code
	g.require(getCurrentUserResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCurrentUserResponse) SetMessage(message string) {
	g.Message = message
	g.require(getCurrentUserResponseFieldMessage)
}

// SetDetails sets the Details field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCurrentUserResponse) SetDetails(details map[string]any) {
	g.Details = details
	g.require(getCurrentUserResponseFieldDetails)
}

func (g *GetCurrentUserResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetCurrentUserResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetCurrentUserResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetCurrentUserResponse) MarshalJSON() ([]byte, error) {
	type embed GetCurrentUserResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetCurrentUserResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getCurrentUserResponseDataFieldUser = big.NewInt(1 << 0)
)

type GetCurrentUserResponseData struct {
	User *User `json:"user" url:"user"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetCurrentUserResponseData) GetUser() *User {
	if g == nil {
		return nil
	}
	return g.User
}

func (g *GetCurrentUserResponseData) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetCurrentUserResponseData) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetUser sets the User field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCurrentUserResponseData) SetUser(user *User) {
	g.User = user
	g.require(getCurrentUserResponseDataFieldUser)
}

func (g *GetCurrentUserResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler GetCurrentUserResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetCurrentUserResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetCurrentUserResponseData) MarshalJSON() ([]byte, error) {
	type embed GetCurrentUserResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetCurrentUserResponseData) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}
