// Code generated by Fern. DO NOT EDIT.

package records

import (
	context "context"

	funcateservergosdk "github.com/lawrencexu/funcate-server-go-sdk"
	core "github.com/lawrencexu/funcate-server-go-sdk/core"
	internal "github.com/lawrencexu/funcate-server-go-sdk/internal"
	option "github.com/lawrencexu/funcate-server-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns a paginated records list from a table or view, supporting sorting, filtering, and other query operations. Note: Depending on the table's listRule, the access to this action may or may not have been restricted.
//
// Example:
//
//	request := &funcateservergosdk.ListRecordsRequest{
//	    LitedbSlug: "<LITEDB_SLUG>",
//	    TableID: "<TABLE_ID>",
//	    Sort: funcateservergosdk.String(
//	        "-created,id",
//	    ),
//	    Filter: funcateservergosdk.String(
//	        "(title~'abc' && created>'2022-01-01')",
//	    ),
//	    Fields: funcateservergosdk.String(
//	        "*",
//	    ),
//	}
//	client.Records.ListRecords(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListRecords(
	ctx context.Context,
	request *funcateservergosdk.ListRecordsRequest,
	opts ...option.RequestOption,
) (*funcateservergosdk.ListRecordsResponse, error) {
	response, err := c.WithRawResponse.ListRecords(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Creates a new record in the specified table. Note: This operation is only supported for tables, not for views. Depending on the table's create rule, the access to this action may or may not have been restricted. When primary key is not auto increment, then must specify the primary key `id` value in the request body.
//
// Example:
//
//	request := &funcateservergosdk.CreateRecordBody{
//	    LitedbSlug: "<LITEDB_SLUG>",
//	    TableID: "<TABLE_ID>",
//	    Fields: funcateservergosdk.String(
//	        "*",
//	    ),
//	    Body: map[string]any{
//	        "active": true,
//	        "id": "97cc3d3d-3804-4669-97b9-567572fb6653",
//	        "title": "Example record",
//	    },
//	}
//	client.Records.CreateRecord(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateRecord(
	ctx context.Context,
	request *funcateservergosdk.CreateRecordBody,
	opts ...option.RequestOption,
) (*funcateservergosdk.GetRecordResponse, error) {
	response, err := c.WithRawResponse.CreateRecord(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns a single record by its ID. Note: When using a view name (tableOrViewName), only list and get operations are supported. Depending on the table's view rule, the access to this action may or may not have been restricted.
//
// Example:
//
//	request := &funcateservergosdk.GetRecordRequest{
//	    LitedbSlug: "<LITEDB_SLUG>",
//	    TableID: "<TABLE_ID>",
//	    RecordID: "<RECORD_ID>",
//	    Fields: funcateservergosdk.String(
//	        "*",
//	    ),
//	}
//	client.Records.GetRecord(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetRecord(
	ctx context.Context,
	request *funcateservergosdk.GetRecordRequest,
	opts ...option.RequestOption,
) (*funcateservergosdk.GetRecordResponse, error) {
	response, err := c.WithRawResponse.GetRecord(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Deletes a single record by its ID. Note: This operation is only supported for tables, not for views. Depending on the table's delete rule, the access to this action may or may not have been restricted.
//
// Example:
//
//	request := &funcateservergosdk.DeleteRecordRequest{
//	    LitedbSlug: "<LITEDB_SLUG>",
//	    TableID: "<TABLE_ID>",
//	    RecordID: "<RECORD_ID>",
//	}
//	client.Records.DeleteRecord(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) DeleteRecord(
	ctx context.Context,
	request *funcateservergosdk.DeleteRecordRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.DeleteRecord(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Updates a single record by its ID. Note: This operation is only supported for tables, not for views. Depending on the table's update rule, the access to this action may or may not have been restricted.
//
// Example:
//
//	request := &funcateservergosdk.UpdateRecordBody{
//	    LitedbSlug: "<LITEDB_SLUG>",
//	    TableID: "<TABLE_ID>",
//	    RecordID: "<RECORD_ID>",
//	    Fields: funcateservergosdk.String(
//	        "*",
//	    ),
//	    Body: map[string]any{
//	        "active": false,
//	        "title": "Updated record",
//	    },
//	}
//	client.Records.UpdateRecord(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) UpdateRecord(
	ctx context.Context,
	request *funcateservergosdk.UpdateRecordBody,
	opts ...option.RequestOption,
) (*funcateservergosdk.GetRecordResponse, error) {
	response, err := c.WithRawResponse.UpdateRecord(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
