// Code generated by Fern. DO NOT EDIT.

// Operations related to individual data records within tables or views.
// When using a view name for tableId, only list and get operations are supported.
// This API serves both client-api and server-api interfaces.
package records
