// Code generated by Fern. DO NOT EDIT.

package sessions

import (
	context "context"
	http "net/http"

	funcateservergosdk "github.com/lawrencexu/funcate-server-go-sdk"
	core "github.com/lawrencexu/funcate-server-go-sdk/core"
	internal "github.com/lawrencexu/funcate-server-go-sdk/internal"
	option "github.com/lawrencexu/funcate-server-go-sdk/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) ListSessions(
	ctx context.Context,
	request *funcateservergosdk.ListSessionsRequest,
	opts ...option.RequestOption,
) (*core.Response[*funcateservergosdk.ListSessionsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://hsm-jianliprod.funcate.com.cn/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/agents/%v/owners/%v/sessions",
		request.AgentSlug,
		request.OwnerID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *funcateservergosdk.ListSessionsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*funcateservergosdk.ListSessionsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateSession(
	ctx context.Context,
	request *funcateservergosdk.CreateSessionRequest,
	opts ...option.RequestOption,
) (*core.Response[*funcateservergosdk.CreateSessionResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://hsm-jianliprod.funcate.com.cn/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/agents/%v/owners/%v/sessions",
		request.AgentSlug,
		request.OwnerID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *funcateservergosdk.CreateSessionResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*funcateservergosdk.CreateSessionResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetSession(
	ctx context.Context,
	request *funcateservergosdk.GetSessionRequest,
	opts ...option.RequestOption,
) (*core.Response[*funcateservergosdk.GetSessionResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://hsm-jianliprod.funcate.com.cn/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/agents/%v/owners/%v/sessions/%v",
		request.AgentSlug,
		request.OwnerID,
		request.SessionID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *funcateservergosdk.GetSessionResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*funcateservergosdk.GetSessionResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) DeleteSession(
	ctx context.Context,
	request *funcateservergosdk.DeleteSessionRequest,
	opts ...option.RequestOption,
) (*core.Response[*funcateservergosdk.DeleteSessionResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://hsm-jianliprod.funcate.com.cn/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/agents/%v/owners/%v/sessions/%v",
		request.AgentSlug,
		request.OwnerID,
		request.SessionID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *funcateservergosdk.DeleteSessionResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*funcateservergosdk.DeleteSessionResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
