// Code generated by Fern. DO NOT EDIT.

package authentication_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	funcateservergosdk "github.com/lawrencexu/funcate-server-go-sdk"
	client "github.com/lawrencexu/funcate-server-go-sdk/client"
	option "github.com/lawrencexu/funcate-server-go-sdk/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestAuthenticationGetAuthMethodsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &funcateservergosdk.GetAuthMethodsRequest{
		AuthSlug: "<AUTH_SLUG>",
	}
	_, invocationErr := client.Authentication.GetAuthMethods(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAuthenticationGetAuthMethodsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAuthenticationGetAuthMethodsWithWireMock", "GET", "/auths/<AUTH_SLUG>/methods", nil, 1)
}

func TestAuthenticationAuthWithPasswordWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &funcateservergosdk.AuthWithPasswordRequest{
		AuthSlug: "<AUTH_SLUG>",
		Username: "johndoe",
		Password: "password123",
	}
	_, invocationErr := client.Authentication.AuthWithPassword(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAuthenticationAuthWithPasswordWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAuthenticationAuthWithPasswordWithWireMock", "POST", "/auths/<AUTH_SLUG>/withPassword", nil, 1)
}

func TestAuthenticationAuthRefreshWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &funcateservergosdk.AuthRefreshRequest{
		AuthSlug: "<AUTH_SLUG>",
	}
	_, invocationErr := client.Authentication.AuthRefresh(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAuthenticationAuthRefreshWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAuthenticationAuthRefreshWithWireMock", "POST", "/auths/<AUTH_SLUG>/refresh", nil, 1)
}

func TestAuthenticationGetPublicTokenWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &funcateservergosdk.GetPublicTokenRequest{
		AuthSlug: "<AUTH_SLUG>",
	}
	_, invocationErr := client.Authentication.GetPublicToken(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAuthenticationGetPublicTokenWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAuthenticationGetPublicTokenWithWireMock", "GET", "/auths/<AUTH_SLUG>/public", nil, 1)
}
