// Code generated by Fern. DO NOT EDIT.

package messages

import (
	context "context"

	funcateservergosdk "github.com/lawrencexu/funcate-server-go-sdk"
	core "github.com/lawrencexu/funcate-server-go-sdk/core"
	internal "github.com/lawrencexu/funcate-server-go-sdk/internal"
	option "github.com/lawrencexu/funcate-server-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// List messages within a session for an owner with optional pagination
//
// Example:
//
//	request := &funcateservergosdk.ListMessagesRequest{
//	    AgentSlug: "<AGENT_SLUG>",
//	    OwnerID: "<OWNER_ID>",
//	    SessionID: "<SESSION_ID>",
//	    Sort: funcateservergosdk.String(
//	        "-created_at",
//	    ),
//	    Filter: funcateservergosdk.String(
//	        "(author='user' && created_at>1732924800000)",
//	    ),
//	    Fields: funcateservergosdk.String(
//	        "id,author,created_at",
//	    ),
//	}
//	client.Messages.ListMessages(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListMessages(
	ctx context.Context,
	request *funcateservergosdk.ListMessagesRequest,
	opts ...option.RequestOption,
) (*funcateservergosdk.ListMessagesResponse, error) {
	response, err := c.WithRawResponse.ListMessages(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a new message within a session for an owner
//
// Example:
//
//	request := &funcateservergosdk.CreateMessageRequest{
//	    AgentSlug: "<AGENT_SLUG>",
//	    OwnerID: "<OWNER_ID>",
//	    SessionID: "<SESSION_ID>",
//	    Author: funcateservergosdk.CreateMessageRequestAuthorUser,
//	    Parts: []*funcateservergosdk.MessagePart{
//	        &funcateservergosdk.MessagePart{
//	            Type: funcateservergosdk.MessagePartTypeText,
//	            Text: funcateservergosdk.String(
//	                "Hello, how can I help you?",
//	            ),
//	        },
//	    },
//	}
//	client.Messages.CreateMessage(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateMessage(
	ctx context.Context,
	request *funcateservergosdk.CreateMessageRequest,
	opts ...option.RequestOption,
) (*funcateservergosdk.CreateMessageResponse, error) {
	response, err := c.WithRawResponse.CreateMessage(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
