// Code generated by Fern. DO NOT EDIT.

package users

import (
	context "context"

	funcateservergosdk "github.com/lawrencexu/funcate-server-go-sdk"
	core "github.com/lawrencexu/funcate-server-go-sdk/core"
	internal "github.com/lawrencexu/funcate-server-go-sdk/internal"
	option "github.com/lawrencexu/funcate-server-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Create a new user account with username and password
//
// Example:
//
//	request := &funcateservergosdk.CreateUserRequest{
//	    AuthSlug: "<AUTH_SLUG>",
//	    Username: "johndoe",
//	    Password: "password123",
//	    PasswordConfirm: "password123",
//	}
//	client.Users.CreateUser(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateUser(
	ctx context.Context,
	request *funcateservergosdk.CreateUserRequest,
	opts ...option.RequestOption,
) (*funcateservergosdk.CreateUserResponse, error) {
	response, err := c.WithRawResponse.CreateUser(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve the currently logged in user's profile
//
// Example:
//
//	request := &funcateservergosdk.GetCurrentUserRequest{
//	    AuthSlug: "<AUTH_SLUG>",
//	}
//	client.Users.GetCurrentUser(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetCurrentUser(
	ctx context.Context,
	request *funcateservergosdk.GetCurrentUserRequest,
	opts ...option.RequestOption,
) (*funcateservergosdk.GetCurrentUserResponse, error) {
	response, err := c.WithRawResponse.GetCurrentUser(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
