// Code generated by Fern. DO NOT EDIT.

package users

import (
	context "context"
	http "net/http"

	funcateservergosdk "github.com/lawrencexu/funcate-server-go-sdk"
	core "github.com/lawrencexu/funcate-server-go-sdk/core"
	internal "github.com/lawrencexu/funcate-server-go-sdk/internal"
	option "github.com/lawrencexu/funcate-server-go-sdk/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) CreateUser(
	ctx context.Context,
	request *funcateservergosdk.CreateUserRequest,
	opts ...option.RequestOption,
) (*core.Response[*funcateservergosdk.CreateUserResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://hsm-jianliprod.funcate.com.cn/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/auths/%v/users",
		request.AuthSlug,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *funcateservergosdk.CreateUserResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*funcateservergosdk.CreateUserResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetCurrentUser(
	ctx context.Context,
	request *funcateservergosdk.GetCurrentUserRequest,
	opts ...option.RequestOption,
) (*core.Response[*funcateservergosdk.GetCurrentUserResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://hsm-jianliprod.funcate.com.cn/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/auths/%v/users/current",
		request.AuthSlug,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *funcateservergosdk.GetCurrentUserResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*funcateservergosdk.GetCurrentUserResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
