// Code generated by Fern. DO NOT EDIT.

package authentication

import (
	context "context"

	funcateservergosdk "github.com/lawrencexu/funcate-server-go-sdk"
	core "github.com/lawrencexu/funcate-server-go-sdk/core"
	internal "github.com/lawrencexu/funcate-server-go-sdk/internal"
	option "github.com/lawrencexu/funcate-server-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns the supported authentication methods
//
// Example:
//
//	request := &funcateservergosdk.GetAuthMethodsRequest{
//	    AuthSlug: "<AUTH_SLUG>",
//	}
//	client.Authentication.GetAuthMethods(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetAuthMethods(
	ctx context.Context,
	request *funcateservergosdk.GetAuthMethodsRequest,
	opts ...option.RequestOption,
) (*funcateservergosdk.AuthMethodsResponse, error) {
	response, err := c.WithRawResponse.GetAuthMethods(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Login with username and password
//
// Example:
//
//	request := &funcateservergosdk.AuthWithPasswordRequest{
//	    AuthSlug: "<AUTH_SLUG>",
//	    Username: "johndoe",
//	    Password: "secret_password",
//	}
//	client.Authentication.AuthWithPassword(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) AuthWithPassword(
	ctx context.Context,
	request *funcateservergosdk.AuthWithPasswordRequest,
	opts ...option.RequestOption,
) (*funcateservergosdk.AuthWithPasswordResponse, error) {
	response, err := c.WithRawResponse.AuthWithPassword(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Refresh JWT token using existing JWT token
//
// Example:
//
//	request := &funcateservergosdk.AuthRefreshRequest{
//	    AuthSlug: "<AUTH_SLUG>",
//	}
//	client.Authentication.AuthRefresh(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) AuthRefresh(
	ctx context.Context,
	request *funcateservergosdk.AuthRefreshRequest,
	opts ...option.RequestOption,
) (*funcateservergosdk.AuthRefreshResponse, error) {
	response, err := c.WithRawResponse.AuthRefresh(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get a public token for accessing public endpoints
//
// Example:
//
//	request := &funcateservergosdk.GetPublicTokenRequest{
//	    AuthSlug: "<AUTH_SLUG>",
//	}
//	client.Authentication.GetPublicToken(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetPublicToken(
	ctx context.Context,
	request *funcateservergosdk.GetPublicTokenRequest,
	opts ...option.RequestOption,
) (*funcateservergosdk.AuthPublicResponse, error) {
	response, err := c.WithRawResponse.GetPublicToken(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
